In [1]:
import sys
import os

import streamlit as st
from core.utils import Sermon, Person, get_short_info
from collections import Counter

import plotly.express as px
from plotly.subplots import make_subplots
import networkx as nx

import plotly.graph_objects as go
import pandas as pd

import json
import re

from rapidfuzz import fuzz

In [15]:
from nltk.corpus import stopwords
german_stop_words = set(stopwords.words('german'))
em_stopwords = []
for stopword in german_stop_words:
    if "i" in stopword:
        em_stopwords.append(stopword)
        em_stopwords.append(stopword.replace("i", "j"))
        em_stopwords.append(stopword.replace("i", "y"))
    elif "u" in stopword:
        em_stopwords.append(stopword)
        em_stopwords.append(stopword.replace("u", "v"))
    else:
        em_stopwords.append(stopword)

em_stopwords = set(em_stopwords)

In [3]:
sermon = Sermon("E000036")

In [8]:
sermon.chunked[8]

[{'words': ['herrn', 'carl', 'christian', 'lange,'],
  'types': ['', '', '', ''],
  'references': [[], [], [], []]},
 {'words': ['hochverdienten',
   'herrn',
   'rathsverwandten',
   'und',
   'zu',
   'der',
   'zeit',
   'hochpreißlich',
   'gewesenen',
   'hospitalsherrn,'],
  'types': ['', '', '', '', '', '', '', '', '', ''],
  'references': [[], [], [], [], [], [], [], [], [], []]},
 {'words': ['seiner',
   'hohen',
   'und',
   'mit',
   'tiefstem',
   'respect',
   'zu',
   'verehrenden',
   'obrigkeit'],
  'types': ['', '', '', '', '', '', '', '', ''],
  'references': [[], [], [], [], [], [], [], [], []]}]

In [10]:
words = sermon.chunked[8][1]["words"]

words

['hochverdienten',
 'herrn',
 'rathsverwandten',
 'und',
 'zu',
 'der',
 'zeit',
 'hochpreißlich',
 'gewesenen',
 'hospitalsherrn,']

In [11]:
[word for word in words if word not in em_stopwords]

['hochverdienten',
 'herrn',
 'rathsverwandten',
 'zeit',
 'hochpreißlich',
 'gewesenen',
 'hospitalsherrn,']

In [16]:
verse = "hr Chriften gut / Habt frischen Muth/ Den Raub habn wir bekommen/ Gerechtigkeit Ist unsre Bent/Wir sind der Furcht entnommen/ Hier ist die Beut/Gerechtigkeit/ Nun sind wir Gottes Kinder/ Drum singn wir all Mit Freudenschall: Danck sey dem Uberwinder"

In [17]:
[word.lower() for word in verse.split() if word.lower() not in em_stopwords]

['hr',
 'chriften',
 'gut',
 '/',
 'habt',
 'frischen',
 'muth/',
 'raub',
 'habn',
 'bekommen/',
 'gerechtigkeit',
 'unsre',
 'bent/wir',
 'furcht',
 'entnommen/',
 'beut/gerechtigkeit/',
 'gottes',
 'kinder/',
 'drum',
 'singn',
 'all',
 'freudenschall:',
 'danck',
 'sey',
 'uberwinder']

In [27]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [125]:
def is_id(value):
    pattern = re.compile(r'E[01][0-9]{5}')
    if re.match(pattern, value):
        return True
    else:
        return False

In [28]:
def create_quote_dist_chart(ids: list, type: str, searchkey: str="") -> go.Figure:
    type_dict = {
        "orgelpredigt": "Orgelpredigtzitate",
        "musikwerk": "Liedzitate",
        "quelle": "Literaturzitate",
    }
    if type not in type_dict.keys():
        occ_fig = go.Figure()
        occ_fig.update_layout(title_text="Type not recognised!")
        return occ_fig
    
    else:
        chunked_text = [0]*100
        thumbnails = [""]*100

        for id in ids:
            sermon = Sermon(id)

            dec = int(len(sermon.words) / 99)
            overhang = len(sermon.words) % dec

            for i, j in zip(range(0, len(sermon.words), dec), range(0, 100)):
                if searchkey != "":
                    keys_unique = sermon.reference[i:i+dec]
                    keys_str = " ".join(flatten(keys_unique))
                    if searchkey in keys_str:
                        hit_test = 1
                        hit = f"{sermon.kurztitel}"
                    else:
                        hit_test = 0
                        hit = ""
                else:
                    types_unique = list(set(sermon.word_types[i:i+dec]))
                    types_str = " ".join([x for x in types_unique if isinstance(x, str)])
                    if type in types_str:
                        hit_test = 1
                        hit = f"{sermon.kurztitel}<br>"
                    else:
                        hit_test = 0
                        hit = ""
                
                chunked_text[j] = chunked_text[j] + hit_test
                thumbnails[j] = thumbnails[j] + hit
            if searchkey != "":
                last_keys_unique = sermon.reference[-overhang:]
                last_keys_str = " ".join(flatten(last_keys_unique))
                if searchkey in last_keys_str:
                    last_hit_test = 1
                    last_hit = f"{sermon.kurztitel}<br>"
                else:
                    last_hit_test = 0
                    last_hit = ""
            else:
                last_types_unique = list(set(sermon.word_types[-overhang:]))
                last_types_str = " ".join([x for x in last_types_unique if isinstance(x, str)])
                if type in last_types_str:
                    last_hit_test = 1
                    last_hit = f"{sermon.kurztitel}<br>"
                else:
                    last_hit_test = 0
                    last_hit = ""
            
            #chunked_text[-1] = chunked_text[-1] + last_orgelpredigt_test
            #thumbnails[-1] = thumbnails[-1] + last_hit

        occ_fig = go.Figure()

        for i in range(0, len(chunked_text)):
            hovertext = f'{chunked_text[i]} {type_dict[type]} im {i+1}%'
            if thumbnails[i] != "":
                    hovertext += f"<br>{thumbnails[i]}"

            gradient = chunked_text[i] * 15
            color = f'rgb({max(250-gradient, 0)},{max(250-gradient, 0)},{max(250-gradient, 0)})'
            occ_fig.add_trace(go.Bar(
                x = [f"{type_dict[type]} je Predigtprozent"],
                y = [100],
                marker_color = color,
                hovertext = hovertext
            ))

        occ_fig.update_layout(width=1500,height=500, showlegend=False)
        print(hit)
        return occ_fig

def group_sermons_in_years(data, interval: int) -> list:
    chunked_sermons = []
    start_year = 1600
    end_year = 1800
    yearfinder = re.compile(r'[0-9]{4}')
    for i in range(start_year, end_year, interval):
        sermons = []
        for id, info in data.items():
            year = int(re.findall(yearfinder, info['year'])[0])
            if year > i and year < i + interval:
                sermons.append(id)
        chunked_sermons.append(sermons)

    return chunked_sermons

In [29]:
# Get the list of all files in a directory
with open("predigten_übersicht.json", "r", encoding="utf-8") as file: 
    data = json.load(file)

# Ensure all entries have a 'year' key
cleaned = {k: v for k, v in data.items() if 'year' in v}

year_finder = re.compile(r'[0-9]{4}')

for k, v in data.items():
    year = re.findall(year_finder, v['year'])[0]
    if year:
        v['year'] = year
    else:
        v['year'] = '[s.a.]'

# Convert to nested list and sort by year
relevant_sermons = sorted(
    [[key, value['title'], int(value['year'])] for key, value in cleaned.items()],
    key=lambda x: x[2]
)

ids = [i[0] for i in relevant_sermons]

In [31]:
praetorius = "E080223"
in_dulci = "E100017"
dieterich = "E000003"
morgenstern = "E100022"

In [32]:
quote_time_dist = "gesamter_zeitraum"
quote_type = "musikwerk"
searchkey = morgenstern

In [33]:
if quote_time_dist == "50-Jahr-Intervalle":
    sermons_grouped_50 = group_sermons_in_years(data, 50)
    figs_50 = []
    for i in range(len(sermons_grouped_50)):
        figs_50.append(create_quote_dist_chart(sermons_grouped_50[i], quote_type,searchkey=searchkey))
    
    # Create subplots
    fig = make_subplots(rows=len(figs_50), 
                        cols=1, 
                        subplot_titles=[f"Verteilung in Predigten zwischen {1600 + (i*50)} und {1600+(i*50)+50} ({len(sermons_grouped_50[i])} Predigten)" for i in range(len(figs_50))])

    # Add traces from each figure to the subplots
    for i, fig_item in enumerate(figs_50):
        for trace in fig_item.data:
            fig.add_trace(trace, row=i+1, col=1)

    # Update layout
    fig.update_layout(height=1200, width=1000, showlegend = False)
    fig.update_layout(title_text="Accumulierte Verteilung von Zitaten in 50-Jahr Intervallen")

elif quote_time_dist == "25-Jahr-Intervalle":
    sermons_grouped_25 = group_sermons_in_years(data, 25)
    figs_25 = []
    for i in range(len(sermons_grouped_25)):
        figs_25.append(create_quote_dist_chart(sermons_grouped_25[i], quote_type,searchkey=searchkey))
    
    # Create subplots
    fig = make_subplots(rows=len(figs_25), 
                        cols=1, 
                        subplot_titles=[f"Verteilung in Predigten zwischen {1600 + (i*25)} und {1600+(i*25)+25} ({len(sermons_grouped_25[i])} Predigten)" for i in range(len(figs_25))])

    # Add traces from each figure to the subplots
    for i, fig_item in enumerate(figs_25):
        for trace in fig_item.data:
            fig.add_trace(trace, row=i+1, col=1)

    # Update layout
    fig.update_layout(height=1200, width=1000, showlegend = False)
    fig.update_layout(title_text="Accumulierte Verteilung von Zitaten in 25-Jahr Intervallen")

else:
    fig = create_quote_dist_chart(ids, quote_type, searchkey=searchkey)

fig.show()

In [34]:
sermon = Sermon("E000036")
quoted_item = "E100022"
passages = []
for i in range(len(sermon.chunked)):
    for j in range(len(sermon.chunked[i])):
        words = sermon.chunked[i][j]["words"]
        types = sermon.chunked[i][j]["types"]
        refs = sermon.chunked[i][j]["references"]
        test_refs = []
        for nr, ref in enumerate(refs):
            if quoted_item in ref:
                test_refs.append(nr)
        if len(test_refs):
            passages.append(" ".join(words))

In [35]:
passages

['zwingt die säiten in cithara,',
 'und laßt die süsse musica gantz freudenreich erschallen,',
 'daß ich möge mit jesulein,',
 'dem wunderschönen bräutgam mein,',
 'jn steter liebe wallen.',
 'singet, springet, jubiliret, triumphiret,',
 'danckt dem herren, groß ist der könig der ehren!',
 'singet, springet, jubiliret, triumphiret,',
 'danckt dem herren, groß ist der könig der ehren.']

In [ ]:
#def get_neighbouring_quotes(sermon_chunked, par_nr, sent_nr, id):
#    par = sermon_chunked[par_nr]

In [116]:
def get_shared_quotes(quoted_item: str, ids: list):
    shared_quotes = []
    for id in ids:
        sermon = Sermon(id)
        for par in sermon.chunked:
            refs = flatten(flatten([x["references"] for x in par]))
            if quoted_item in refs:
                shared_quotes.extend(refs)
    return [x for x in shared_quotes if x != quoted_item]

In [122]:
"Sir_43".split("-")

['Sir_43']

In [135]:
morgenstern_adjacent_quotes = get_shared_quotes(morgenstern, ids)
morgenstern_adjacent_quotes = [x.split("-")[0] for x in morgenstern_adjacent_quotes]
morgenstern_adjacent_quotes = [get_short_info(x) if is_id(x) else x for x in morgenstern_adjacent_quotes]
morgenstern_adjacent_quotes = [x.split(":")[1] if len(x.split(":")) > 1 else x for x in morgenstern_adjacent_quotes]

In [139]:
counts = Counter(morgenstern_adjacent_quotes)
top20 = counts.most_common(20)

# Sort by frequency (descending)
sorted_items = counts.most_common()
labels = [item[0] for item in top20]
values = [item[1] for item in top20]

# Plot with Plotly
fig = px.bar(
    x=labels, 
    y=values, 
    labels={'x': 'Quelle', 'y': 'Häufigkeit'},
    title="20 am häufigsten mit 'Wie schön leuchtet der Morgenstern' im selben Paragraph erscheinenden Quellen/Lieder"
)
fig.show()

In [142]:
def get_quoted_passages(quoted_item: str, ids: list):
    # get passages from quoted item in every sermon
    passages = []
    for id in ids:
        sermon = Sermon(id)
        for i in range(len(sermon.chunked)):
            for j in range(len(sermon.chunked[i])):
                words = sermon.chunked[i][j]["words"]
                types = sermon.chunked[i][j]["types"]
                refs = sermon.chunked[i][j]["references"]
                test_refs = []
                for nr, ref in enumerate(refs):
                    if quoted_item in ref:
                        test_refs.append(nr)
                if len(test_refs):
                    if j > 0:
                        words_before = " ".join(sermon.chunked[i][j-1]["words"])
                    else:
                        words_before = " ".join(sermon.chunked[i-1][-1]["words"])
                    if j < len(sermon.chunked[i])-1:
                        words_after = " ".join(sermon.chunked[i][j+1]["words"])
                    else:
                        words_after = " ".join(sermon.chunked[i+1][0]["words"])
                    passages.append([id, i, j, " ".join(words), words_before, words_after])
    
    return passages

passages = get_quoted_passages(morgenstern, ids)

In [11]:
dieterich_text = Sermon("E000003").chunked

In [15]:
dieterich_text[0][0]

{'words': ['vlmische',
  'orgel',
  'predigt/',
  'darinn',
  'von',
  'der',
  'jnstrumentalmusic',
  'inns',
  'gemein/'],
 'types': ['', '', '', '', '', '', '', '', ''],
 'references': [[], [], [], [], [], [], [], [], []]}

In [16]:
dieterich_verses = []
for par in dieterich_text:
    for sent in par:
        dieterich_verses.append(" ".join(sent['words']))
dieterich_verses

['vlmische orgel predigt/ darinn von der jnstrumentalmusic inns gemein/',
 'sonderlich aber von dero orgeln erfindung vnd gebrauch/',
 'in der kirchen gottes/',
 'von anfang der welt biß hieher,',
 'kürtzlich discurriret, zugleich auch die schöne herrliche vlmer orgel beschrieben wirdt.',
 'gehalten zu vlm im münster/',
 'an dessen kirchweyhtag/ den 1.',
 'augusti dieses 1624. jahrs/',
 'vnd auff begehren in offenen truck geben/',
 'durch cunrad dieterich/ der heiligen schrifft doctorn/',
 'dero vlmischen kirchen superintendenten.',
 'gedruckt zu vlm in der mederischen truckerey.',
 'm. dc. xxiv',
 'vakat',
 'ehrnvöster/ vornehmer/ insonders geliebter herr vnd freundt/',
 'demnach ich ohnlangst bey vnserer nechstverwichnen kirchwey/',
 'ein christliche einfältige sermon/',
 'von der jnstrumentalmusic vnd orgeln gehalten/',
 'darinn ich von dem ersten brauch der musicalischen jnstrumenten/',
 'beym gottesdienst ins gemein/',
 'besonders aber deren orgeln/',
 'einen kurtz durchgehenden discurs gehalten/',
 'vnd aber/ daß ich selbigen in offnen truck publiciren vnd außgehen lassen wolle/',
 'von etzlichen guthertzigen der kirchenmusicliebhabenden/',
 'von mir begehrt worden:',
 'als hab ich denselbigen bevorderst/',
 'dann auch andern ins gemein/',
 'zu gutem willen hierin gern in rei memoriam gratificiren wöllen/',
 'vnangesehen mir nit bewust/',
 'daß darinn was sonderbares/',
 'so von andern/ der edlen musicalischen kunst wolbenambten rühmern/',
 'nicht besser tractiret vnd herauß gestrichen/',
 'zu finden seyn werde.',
 'solche aber hab ich dem herrn dero vrsachen zuschreiben wollen/',
 'weil nicht allein sein lieber alter vater/',
 'herr adam steigleder/ mein sonders guter angenemer freund/',
 'nunmehr in das dreissigste jahr/',
 'vnserer vlmischen weitberuffnen vnd berümbten orgel/',
 'mit guten ehren vnd meniglichs löblichem ruhm vorgestanden.',
 'sondern er selbsten auch vor andern in der löblichen orgelkunst dermassen geübt vnd erfahren /',
 'daß er mit guten ehren für einen meister darinn passiren kan.',
 'gestalt dann seine/ so wol bey vns newlicher zeit/',
 'mit nicht geringem belieben angehörte specimina,',
 'als auch die bey sich habende allerhand schöne/',
 'liebliche/ kunstreiche compositiones, mehr dann gnug im werck selbsten bewehrten vnd außweisen;',
 'welche der edlen music vnd orgelkunst zu ehren/',
 'ans tagliecht zugeben/ ich jhne hiemit veranlassen/',
 'auch zugleich meine gute wolgeneigte affection,',
 'gegen jhn vnd die seinen/',
 'zuerkennen geben wollen/ mitt bitt/',
 'er dieselbig zu freundtlichem willen auff vnd annemmen/',
 'vnnd meiner darbey im besten eingedenck sein/',
 'auch den guten alten künstler/',
 'herrn cunrad schotten/ welcher mit seinen blinden augen bey vnserer vlmischen orgel weyt mehr/',
 'als andere mit beeden augen sehende meister/',
 'gesehen/ vnd selbiger zu jhrer verbesserung vnd perfection durch sein kunst vor der zeit auffgeholffen/',
 'mein freundtlichen gruß beneben allem gutem vermelden wolle:',
 'thue jhn hiemit gottlicher gnaden protection zu erwünschtem wolstand befehlen:',
 'geben inn vlm den 18.',
 'augusti/ ablauffendens 1624. jahrs.',
 'dessen freundwilliger chunrad dieterich d.',
 'vers. 1.',
 'lobet den herrn inn seinem heyligthumb/',
 'lobet jhn in der feste seiner macht.',
 '2. lobet jhn inn seinen thaten/',
 'lobet jhn in seiner grossen herligkeit.',
 '3. lobet jhn mit posaunen/',
 'lobet jhn mit psalter vnd harpffen.',
 '4. lobet jhn mit paucken vnd reigen/',
 'lobet jhn mit sayten vnnd pfeiffen.',
 '5. lobet jhn mit hellen cymbaln/',
 'lobet jhn mit wolklingenden cymbaln.',
 '6. alles was odem hat/',
 'lobe den herren/ alleluja.',
 'es seind auff diesen gegenwertigen heutigen tag/',
 'nuhnmehr 136. jahr/ daß dise vnsere schöne herrliche kirche/',
 'in jhrem baw/ wie sie da noch vor vnsern augen stehet/',
 'vollendet/ vnd demnach/ damahligem päbstischem gewohnlichem brauch gemäß/',
 'zu vnserer lieben frawen münster/',
 'nit allein erstenmals offentlich consecriret vnd eingesegnet/',
 'sondern auch/ daß deren vergangnen kirchwey gedächtnuß/',
 'jährlich auff diesen tag widerholet würde/',
 'angeordnet worden. wann dann nun/',
 'beneben verrichtung vnsers christlichen gewonlichen gottesdiensts/',
 'wir auch zu christlicher begängnuß/',
 'dieser vnserer järlichen kirchweyh/',
 'jetzmahl in gottes namen bey einander versamblet/',
 'dabey dann es dieses orths herkommens/',
 'daß von christlichem kirchenwesen/',
 'vnnd deren zugehörigen stucken/',
 'inn denen kirchweyh predigten gehandelt wirdt:',
 'als wil ebenmässiges mir auch dißmahls zu verrichten obligen.',
 'demnach ich aber hiebevor dergleichen vnderschiedene stuck/',
 'so zum kirchenwesen nothwendig/',
 'abgehandlet/ als nämblich/ 1.',
 'von denen glocken /',
 'damit zur kirchen geleütet wirdt.',
 '2. von dem offentlichen gemeinen choralvnnd figuralkirchengesang/',
 'so inn der kirchen vorgehen soll;',
 'vnd aber zu der choralvnnd figuralmusic/',
 'auch die jnstrumentalmusic gehörig:',
 'so wil jch vor gegenwärtigen jargang dieselbige für mich nemmen/',
 'vnnd inn dieser kirchweyhpredigte allein etwas von der music/',
 'so in christlichen kirchen/',
 'mit vnderschiedenen musicalischen jnstrumenten/',
 'als posaunen/ flöten/ zincken/',
 'pommern/ dolcianen/ vagotten/ schalmeyen/',
 'geygen/ violen/ banduren/ harpffen/',
 'zittern/ clauichordien/ positiuen/ andern dergleichen/',
 'sonderlich auch den orgeln/',
 'verrichtet wirdt/ handlen.',
 'darzu vnns dann verlesne wort deß 150.',
 'psalmens/ deß rechten musicalischen lobpsälmleins/',
 'gute anleitung geben werden/',
 'welche ich 1. schlecht vnd einfältig den worten nach erklären/',
 'vnd dann auch/ was wir darauß von jnstrumentalmusic vnnd orgeln/',
 'werden zubehalten haben/ mit wenigem andeuten wil.',
 'weil denn nuhn david inn diesem vnserem vorhabenden psalmen alles was odem hat/',
 'den herrn zu loben vermanet/',
 'vnd aber ewer lieben sampt vnd sonders mit einem menschlichen odem von gott begnadet:',
 'so wolle dieselbige vmb sovil desto fleissiger vnd andächtiger zu zuhören erbetten seyn.',
 'der grosse mächtige gott so vns allen odem geben/',
 'vnd von vns allen darumb zu loben/',
 'verleyhe hierzu sein gnad von oben herab/',
 'durch christum jesum/ amen.',
 'so vermahnet nun david inn seinem von vns vorgenommenen musicalischen lobpsälmlein/',
 'alle vnd jede menschen/',
 'den herrn zuloben vnd zu preysen:',
 'lobet den herrn/ sagt er.',
 'da er dann durch den herrn verstehet gott den herrn/',
 'welcher der einige herr vnd gott ist/',
 '5. buch mosi 6.4.',
 'dann er der gott aller götter/',
 'vnnd herr vber alle herren/',
 '5. buch mose 10.17.',
 'ausser welchem sonsten keiner mehr/',
 '5. mos. cap. 4.35.',
 'diesen herrn vnd gott wil nun david/',
 'daß jhn alle menschen loben/',
 'theils vmb der feste seiner macht vnnd thaten/',
 'theils vmb seiner grossen herrligkeit willen:',
 'vmb der feste seiner macht/',
 'weil seine macht vnendtlich/',
 'vnd also vnvberwindtlich ist.',
 'herr zebaoth/ wer ist wie du ein mächtiger gott?',
 'psal. 89.9. dannenher er der gott der vnser stärcke ist/',
 'genennet/ psal. 81.2. welche feste seiner macht er sonderlich vnd fürnemblich in schöpffvnd erhaltung aller ding/',
 'in schützregiervnnd führung seiner kirchen/',
 'vnnd aller seiner frommen churkinder/',
 'mächtig erwisen/ vnd noch täglichen erweiset/',
 'deßwegen er dann billich zu leben/',
 'darumb sagt david: lobet jhn in der feste seiner macht/',
 'lobet jhn in seinen thaten.',
 'vmb seiner grossen herrligkeit/',
 'weil dieselbige vnermäßlich vnd vnergründtlich/',
 'wegen seiner vnerforschlichen weißheit/',
 'güte/ trew/ liebe/ gnad/',
 'barmhertzigkeit/ gericht vnd warheit/',
 'dardurch er dise seine herrligkeit erwisen vnd groß gemacht.',
 'o/ welche ein tieffe deß reichthumbs beyde der weißheit vnd erkäntnuß gottes?',
 'wie gar vnbegreifflich sind seine gerichte?',
 'vnd vnerforschlich seine wege?',
 'denn wer hat deß herrn sinn erkannt?',
 'oder/ wer ist sein rathgeber gewesen?',
 'darumben sagt davidt: lobet jhn in seiner grossen herrligkeit.',
 'diß loben soll aber nicht geschehen nuhr mit dem munde/',
 'mit gebett vnd dancksagung/',
 'nicht nur mit der stimme/',
 'mit modulierung geistlicher psalmen vnnd lobgesängen:',
 'sondern auch mit allerhand löblichen/',
 'lieblichen musicalischen jnstrumenten: lobet jhn mit posaunen/',
 'lobet jhn mit psalter vnd harpffen/',
 'lobet jhn mit paucken vnd reygen/',
 'lobet jhn mit saiten vnd pfeiffen/',
 'lobet jhn mit hellen cymbaln/',
 'lobet jhn mit wolklingenden cymbalen.',
 'siebnerley musicalische jnstrument erzehlet allhie david mit welchen man den herren loben soll:',
 'nämlich/ psalter/ harpffen/ posaunen/',
 'paucken/ saiten/ pfeiffen/ cymbalen.',
 'als welche damahls vnder dem volck gottes vor andern vblich vnd bräuchlich gewesen.',
 'wie aber solche jnstrumenta gestalt/',
 'vnd was für ein beschaffenheit es mit jhnen gehabt/',
 'kan man wegen mangel der antiquitäten/',
 'eigentlich nicht wissen/ ohne was josephus der alten jüdischen geschichten schreiber hiervon meldet.',
 'derselbige schreibet aber im viertzehenden buch der jüdischen antiquitäten am 10.',
 'c. gedenckt deren auch sabellicus,',
 'daß der psalter ein jnstrument gewesen/',
 'so zehen sayten gehabt/',
 'vnd mann mit einem plectro oder federkihl schlagen müssen/',
 'deßwegen es auch decachordum,',
 'sonst cinnyra od auch cithara genant/',
 'dergleichen art etwa die cytharn seyn/',
 'so wir heutiges tags gebrauchen:',
 'wiewol hieronymus schreibet/ daß bey den hebreern oder juden die cythar oder psalter vier vnd zweintzig saiten gehabt/',
 'vnnd wie der griechische buchstab δ formiert oder gebildet gewesen/',
 'dergleichen auß josepho vnd hieronymo auch polidorus virgilius erwehnet.',
 'die harpffe ist ein jnstrument gewesen vonn zwölff saiten/',
 'welchs man mit den fingern greiffen müssen/',
 'wirdt sonst nablum oder nabla genandt/',
 'dannenhero vnsere harpffen/ so wir noch heutigs tags gebrauchen jhren nahmen haben.',
 'posaunen hat man mit dem mund geblasen/',
 'darunder dann zincken/ trommeten/',
 'krummhorn/ andere beröhrte jnstrumenta mehr verstanden.',
 'paucken aber hat man mit besonderen schlegelen oder knüppelein geschlagen/',
 'dergleichen noch heutigs tags im brauch.',
 'ohne daß die juden neben den paucken jhre besondere chorvnnd frewdenraygen gehabt.',
 'durch die saitten werden alle jnstrument/',
 'so mit saitten vberzogen/',
 'als geygen/ violen/ lauten/',
 'leyren/ andere dergleichen; durch die pfeiffen/',
 'allerley pfeiffen vnnd flöten angedeutet.',
 'jnn dem hebreischen steht das wort üggaf hebr.,',
 'welchs zu latein jst geben worden organum,',
 'von welchem vnser teutsch wort orgel kommet/',
 'dannenher etzliche inn der meinung/',
 'daß schon zu davidts zeiten die orgel im brauch gewesen.',
 'geben auch die heutige juden auß/',
 'wie michael praetorius schreibt/',
 'daß er selbsten dessen von etlichen juden berichtet/',
 'daß salomon zu seiner zeit ein orgel inn den tempel zu jerusalem setzen lassen/',
 'so er selbsten erfunden vnd angeben/',
 'die so künstliche vnd herrlich gewesen/',
 'daß dise vnsere jetzige orglen wie nichts dargegen zuhalten/',
 'deßwegen dan sie/ die jetzige juden/',
 'keine orgeln hören mögen.',
 'weil aber solches vngewiß/',
 'vnd davon in biblischen vnnd andern historien kein gewisse nachrichtung/',
 'hat d. luther solches für ein besonders pfeiffenwerck gehalten:',
 'wen er aber/ wie es eygentlich damit beschaffen/',
 'nicht wissen können/ hat er darfür in seiner teutschen dolmetschung pfeiffen gesetzt.',
 'cymbaln sind besondere auß ähren gegössene schellen vnd glöcklein gewesen/',
 'deren etzliche klein/ etzliche mittelmässig/',
 'etzliche groß/ daß sie ein anmuetige/',
 'wolklingende symphony/ melodey vnnd hall von sich geben/',
 'deßwegen sie helle vnd wolklingende cymbalen genennet/',
 'dergleichen man noch an vilen orten/',
 'als straßburg/ franckenberg in hessen/',
 'bey den heiligen dreyen königen/',
 'vnd in vnserer nachbawrschafft im closter zu blawbewren bey alten kunstreichen vhrwercken findet/',
 'dardurch besondere auff einander stimmende glöcklein/',
 'besondere lieder geschlagen werden/',
 'wie denen bewußt/ so inn der frembde gewandert/',
 'solche vhrwerck gesehen oder schlagen hören.',
 'mit diesen jüdischen musicalischen jnstrumenten wil david/',
 'sollen sie den herrn loben/',
 'nicht in jhren eygenen oder andern häusern/',
 'sonder in jhrer offenen kirchen vnd zusammenkunfft/',
 'in jhrer offenen gemein/',
 'nämblich im heyligtumb deß herrn.',
 'lobet den herrn inn seinem heyligtumb/',
 'lautet vnser lobpsälmlein. da dann durch das heyligtumb verstanden wirdt das heyligtumb deß tabernaculs/',
 'oder hüten deß stiffts/',
 'deren sich die juden noch zu davids zeiten gebraucheten/',
 'ehe dann der tempel zu jerusalem erbawet.',
 'wirdt aber deß herrn heyligtumb genennet/',
 'weil der herr seines namens gedächtnuß darinn vor andern gestifftet/',
 'die lade deß bundts mit guldinen cherubinen dareinsetzen/',
 'auch sein heyligen gottesdienst hierinn verrichten lassen/',
 'vnd daselbsten sein heilige praesenz vnnd gegenwart den kindern jsrael versprochen/',
 'wie neben andern im 2.',
 'buch mosi am 20.',
 'v 24. zusehen ist.',
 'dergestalt nun soll menniglich den herren loben.',
 'alles was odem hat lobe den herrn/',
 'schleußt david: was menschlichen/',
 'natürlichen odem hat/ soll also den herrn loben.',
 'welchem jnstrument artificial-odem eingeblasen oder sonst eingegeben wirdt/',
 'soll den herrn loben/',
 'vnnd diß jhr stimm sein:',
 'halleluja/ das ist/ lobet den herrn.',
 'das ist nun der einfältige wortverstand vnsers vorgelesnen davidischen lobpsälmleins.',
 'hjerauß hetten wir nuhn wol vnderschiedene lehrpünctlein vom loben deß herrn zu nemmen:',
 'weil aber selbige sampt vnd sonders dißmahl einvnnd außzuführen vnsers intents vnd vorhabens nit ist:',
 'als wöllen wir allein diß mercken/',
 'was david von den psaltern/',
 'harpffen/ posaunen/ paucken/ seiten pfeiffen vnd cymbaln/',
 'mit welchen man den herrn in seinem heyligtumb loben solle/',
 'erwehnung thut. denn darbey werden wir gelehret/',
 'daß man auch die jnstrumentalmusic/',
 'in der christlichen kirchen vnd gemein/',
 'bey verrichtung deß offenen gottesdiensts/',
 'mit gutem fug vnd gewissen brauchen könne vnd möge.',
 'es seind aber solche musicalische jnstrumenten vnderschieden vnd viel/',
 'deren etzliche inflatilia, blasende/',
 'so mit angetriebenem oder geblasnem wind gestimmet werden.',
 'etzliche fidicinia besaitende/ so mit saiten vberzogen vnd durch bewegung deren/',
 'gestimmet werden. die blasende jnstrument sind widerumb zweyerley/',
 'dann deren etliche durch hülff der natürlichen lufft oder wind/',
 'so durch auffziehung der blaßbälge/',
 'in die pfeiffen gelassen wirdt/',
 'durch schlagung der claviren klingend vnd tönend gemacht werden/',
 'als da sind die orgeln positiff vnd regalen.',
 'etzliche werden durch menschlichen odem/',
 'mit dem mund angeblasen:',
 'als posaunen/ trommeten/ zincken/',
 'corneten/ krumhorner/ pommern/ vagotten/',
 'dolcianen/ sordunen/ racketen/ allerley flöten bassanelli/',
 'ander pfeiffen. besaitende jnstrumenta sind/',
 'so mit saiten bezogen/',
 'deren etzliche gemacht von därmen/',
 'wie zu allerhand arten der geigen/',
 'violen/ violuntzen/ lauten/ theorben/',
 'quinternen/ panduren/ harpffen/ etc.',
 'gebrauchet. etzliches gemacht von ertz/',
 'messing/ stählin: mit dergleichen pandorn/',
 'cytharn vnd deren vnderschiedene arten/',
 'clauichordien/ clauiecymblen/ jnstrumenta/ virginal/',
 'geigen jnstrument/ andere ebenmässiger art/',
 'vberzogen werden/ auch vblichen brauchs herbracht worden/',
 'so mit einander auff begebne mittel/',
 'jetzo inn diesem/ dann jenem/',
 'können zur music/ bey christlichem gottesdienst gebührender maß vnd weise gebraucht werden.',
 'denn gleich wie gott der herr ins gemein ein vrheber vnd stiffter der music ist/',
 'welches so gewiß/ daß es plutarchus,',
 'der doch ein heyd gewesen/',
 'auß dem liecht der natur erkennet/',
 'in dem er inn seinem buch von der music neben andern also sagt:',
 'σεμνὴ οὖν κατὰ πάντα ἡ μουσικὴ θεῶν ἕυρημα:',
 ': omnibus modis veneranda est musica,',
 'cùm deorum inventum sit.',
 'also ist die jnstrumentalmusic auch gottes gab/',
 'desßwegen er bald nach erschaffung der welt/',
 'noch bey lebzeiten/ vnsers ersten paradißvatters deß adams/',
 'jubal den andern sohn lamech erwecket/',
 'welcher am aller ersten die jnstrumental music erfunden/',
 'deßwegen er pater omnis tractantis chinnor &amp;',
 'üggaf, ein erfinder der geiger vnnd pfeiffer von mose genennet/',
 'gen. 4.21. da denn durch das wort chinnor alle jnstrument/',
 'so mit saiten bezogen werden/',
 'verstanden. als: clavichordia/ jnstrument/',
 'lauten/ geigen/ harpfen/ pandur/',
 'leyren/ cytharen/ etc. vnder dem wort üggaf aber/',
 'alle so mit dem athem geblasen/',
 'als: posaunen/ zincken/ krummhorn/',
 'trommeten/ pfeiffen/ flöten/ positiven/',
 'regalen/ orgeln/ der gleichen mehr/',
 'weil sie alle vom pfeiffen erstens herkommen vnnd erfunden worden/',
 'verstanden werden. welche ob sie wol von den weltkindern damals zur vppigen weltfrewd mißbrauchet:',
 'so hat doch das volck gottes selbige/',
 'ohn allen zweyfel zu jhrem opfer/',
 'vnd anderem gottes dienst/',
 'gott zu lob vnnd preyß angewendet/',
 'massen diß ab der heydnischen völcker exempel/',
 'handgreiflich abzunehmen.',
 'dann nachdem deß noah nachkommen nach der sündflut in alle welt zerstrewet/',
 'ist zwar der wahre gottes dienst allein beym seth vnnd seinen nachkommen/',
 'darunder abraham mit seiner posteritet gehörig/',
 'blieben. die nachkommene japhets vnnd chams aber/',
 'haben alle miteinander im heydenthumb gelebet/',
 'da sie dann nichts desto weniger/',
 'jhre heydnische götzen opfer vnd götzendienst verrichtet/',
 'vnnd bey demselbigen jhre jnstrumental music/',
 'von pfeiffen/ cymbaln/ paucken/',
 'anderen jnstrumenten gehabt/ nach demselbigen auch jhre opferdäntz/',
 'gesang/ mahlzeit/ jhrem vermainten gott zu ehren/',
 'verrichtet/ wie das exempel der griechen bey plutarcho,',
 'der jnder bey scaligero,',
 'der cureter beim strabone,',
 'der römer beym livio außweist.',
 'welches ohn allen zweyfel sie extra traditione patrum gehabt/',
 'den lieben alten patriarchen abgelehrnet/',
 'vnd deren exempel hierin/',
 'wie wol auff vngezimbte mittel nachöhmen wöllen.',
 'dannenher die kinder jsraël/',
 'da sie trocken durch das rothe meer geführet/',
 'pharao mit aller seiner heeres krafft mit roß vnnd mann ersäufft/',
 'gott zu ehren/ nicht allein ein herrlicher ἐϖινίκιον vnd siglied gesungen/',
 'sondern miriam die schwester mose/',
 'sampt den anderen weibern/',
 'die paucken vnd trummeln darzu geschlagen haben/',
 'wie im andern buch mos.',
 '15.20. zuleßen. ja/ es hat gott der herr selbst seinem volck befohlen/',
 'daß sie sollen posaunen zurichten/',
 'vnd mit denselbigen auff jhren fästen vnd newmonden vber jhre brandvnd danckopfer blasen/',
 'im vierdten buch mos.',
 '10.10. dem also die kinder jraël auch nachgefolget/',
 'die posaunen/ paucken/ harpfen vnd psalter gerühret/',
 'vnnd damit das laubrüsten fest gehalten/',
 'welches ein recht gewesen/',
 'deß gottes jacobs vnd ein weise in jsraël/',
 'wie assaph im 81.',
 'psalm. v. 5. meldet.',
 'da david die lade deß bunds/',
 'auß dem hauß aminadab zu gibea/',
 'deßgleichen auß dem hauß obededom gen jerusalem führen ließ/',
 'da spielten sie auff mit allem saytenspiel von tennenholtz/',
 'mit harpfen/ psaltern vnd paucken/',
 'vnd schellen vnnd cymbaln/',
 'mit jauchtzen vnd posaunen/',
 '2. sam. 6. v.',
 '15. sonderlich hat david nicht nur für sich privatim,',
 'mit harpfen/ psalter vnd saytenspiel gott geehret vnd geprysen:',
 'sondern er hat auch besondere saytenspiel gemacht/',
 'vnnd darzu vier tausent musicanten verordnet.',
 'selbige auch inn jhr besondere stett vnnd chor/',
 'mit jhren jnstrumenten abgethailet/',
 'deren dann in die fünff vnd zwainzig gewesen/',

In [144]:
results = pd.DataFrame(passages, columns=['sermon', 'par', 'sent', 'verse', 'text_before', 'text_after'])

In [39]:
liedtext_morgenstern = [
"Wie schön leuchtet der Morgenstern /",
"Voll Gnad vnd Warheit von dem HERRN /",
"Die süsse Wurtzel Jesse?",
"Du Sohn Dauid auß Jacobs Stamm /",
"Mein König vnd mein Bräutigam /",
"Hast mir mein Hertz besessen /",
"Lieblich freundtlich Schön vnd herrlich /",
"Groß vnd ehrlich Reich von Gaben /",
"Hoch vnd sehr prächtig erhaben.",
"Ey mein Perle / du werthe Kron /",
"Wahr Gottes vnd Marien Sohn /",
"Ein hochgeborner König /",
"Mein Hertz heißt dich ein lilium,",
"Dein süsses Euangelium,",
"Jst lauter Milch vnd Honig /",
"Ey mein Blümlein Hosianna /",
"Himmlisch Manna Das wir essen /",
"Deiner kan ich nicht vergessen.",
"Geuß sehr tieff in mein Hertz hineyn /",
"Du heller Jaspis vnd Rubin /",
"Die Flamme deiner Liebe.",
"Vnd erfreuw mich / daß ich doch bleib",
"An deinem außerwehlten Leib",
"Ein lebendige Rippe /",
"Nach dir ist mir /",
"Gratiosa cœli rosa Kranck vnd glümmet",
"Mein Hertz / durch Liebe verwundet.",
"Von Gott kompt mir ein Frewdenschein /",
"Wenn du mit deinen Eugelein /",
"Mich freundtlich thust anblicken /",
"O HERR Jesu mein trawtes Gut /",
"Dein Wort / dein Geist / dein Leib vnd Blut /",
"Mich innerlich erquicken. Nimm mich /",
"freundtlich Jn dein Arme /",
"Daß ich warme Werd von Gnaden /",
"Auff dein Wort komm ich geladen.",
"HERR Gott Vatter / mein starcker Heldt /",
"Du hast mich ewig / für der Welt /",
"In deinem Sohn geliebet /",
"Dein Sohn hat mich jhm selbst vertrawt /",
"Er ist mein Schatz / ich bin sein Braut /",
"Sehr hoch in jhm erfreuwet.",
"Eya Eya Himmlisch Leben /",
"wirdt er geben Mir dort oben /",
"Ewig soll mein Hertz jhn loben.",
"Zwingt die Sayten in Cythara.",
"Vnd laßt die süsse Musica,",
"Gantz frewdenreich erschallen:",
"Daß ich möge mit Jesulein /",
"Dem wunder schönen Bräutgam mein /",
"In stäter Liebe wallen.",
"Singet springet Jubilieret triumphieret /",
"Danckt dem HERREN Groß ist der König der Ehren.",
"Wie bin ich doch so hertzlich fro /",
"Daß mein Schatz ist das A vnd O /",
"Der Anfang / vnd das Ende:",
"Er wirdt mich doch zu seinem Preyß /",
"Auffnemmen in das Paradeiß /",
"Deß klopff ich in die Hände.",
"Amen Amen Komm du schone",
"FrewdenKrone Bleib du nicht lange /",
"Deiner wart ich mit Verlangen."
]

In [145]:
results

,sermon,par,sent,verse,text_before,text_after
0,E000091,60,0,ey/ mein perle du werthe cron/,was ich gesucht bin ich gewehrt.,wahr gottes und marien sohn/
1,E000091,60,1,wahr gottes und marien sohn/,ey/ mein perle du werthe cron/,ein hochgeborner könig/ mein hertz heisst dich...
2,E000091,60,2,ein hochgeborner könig/ mein hertz heisst dich...,wahr gottes und marien sohn/,dein süsses evangelium/ ist lauter milch und h...
3,E000091,60,3,dein süsses evangelium/ ist lauter milch und h...,ein hochgeborner könig/ mein hertz heisst dich...,ey mein/ blümlein/ hosianna/
4,E000091,60,4,ey mein/ blümlein/ hosianna/,dein süsses evangelium/ ist lauter milch und h...,himlisch manna/ daß wir essen/
5,E000091,60,5,himlisch manna/ daß wir essen/,ey mein/ blümlein/ hosianna/,deiner kan ich nicht vergessen.
6,E000091,60,6,deiner kan ich nicht vergessen.,himlisch manna/ daß wir essen/,zwingt die seiten in cythara/
7,E000091,61,0,zwingt die seiten in cythara/,deiner kan ich nicht vergessen.,vnd lasst die süsse musica/
8,E000091,61,1,vnd lasst die süsse musica/,zwingt die seiten in cythara/,ganz freudenreich erschallen/ daß ich möge mit...
9,E000091,61,2,ganz freudenreich erschallen/ daß ich möge mit...,vnd lasst die süsse musica/,den allerhöchsten bräutgam mein/
10,E000091,61,3,den allerhöchsten bräutgam mein/,ganz freudenreich erschallen/ daß ich möge mit...,jn steter liebe wallen/
11,E000091,61,4,jn steter liebe wallen/,den allerhöchsten bräutgam mein/,singet/ springet/ jubiliret/ triumphiret/
12,E000091,61,5,singet/ springet/ jubiliret/ triumphiret/,jn steter liebe wallen/,danckt dem herrn/ groß ist der könig der ehren.
13,E000091,61,6,danckt dem herrn/ groß ist der könig der ehren.,singet/ springet/ jubiliret/ triumphiret/,vnd so viel vom ersten stück/
14,E000083,20,0,zwingt die saiten in cythara/,2. wem es vorgespielet worden?,und lasst die süsse musica gantz freudenreich ...
15,E000083,20,1,und lasst die süsse musica gantz freudenreich ...,zwingt die saiten in cythara/,singet/ springet/ jubiliret/ triumphiret/
16,E000083,20,2,singet/ springet/ jubiliret/ triumphiret/,und lasst die süsse musica gantz freudenreich ...,danckt dem herren/ groß ist der könig der ehren/
17,E000083,20,3,danckt dem herren/ groß ist der könig der ehren/,singet/ springet/ jubiliret/ triumphiret/,amen.
18,E000083,20,4,amen.,danckt dem herren/ groß ist der könig der ehren/,frolocket mit händen alle völcker/
19,E000079,26,44,zwingt die säiten in cithara/,sollen wir doch dem herrn singen und spielen i...,und last die süsse musica/
20,E000079,26,45,und last die süsse musica/,zwingt die säiten in cithara/,gantz freudenreich erschallen. müssen wir scho...
21,E000079,26,46,gantz freudenreich erschallen. müssen wir scho...,und last die süsse musica/,oder die harpfen an die weide hengen/
22,E000075,15,0,so zwingt demnach die saiten in cithara/,sonst ist all euer gottesdienst eitel und gieb...,und laßt die süße musica gantz freudenreich er...
23,E000075,15,1,und laßt die süße musica gantz freudenreich er...,so zwingt demnach die saiten in cithara/,singet/ klinget/ jubiliret/ triumphiret/
24,E000075,15,2,singet/ klinget/ jubiliret/ triumphiret/,und laßt die süße musica gantz freudenreich er...,danckt dem herren/ groß ist der könig der ehren!
25,E000075,15,3,danckt dem herren/ groß ist der könig der ehren!,singet/ klinget/ jubiliret/ triumphiret/,dir aber/ o du vater des liechts/
26,E000072,15,51,zwingt die saiten in cithara/,43/32. und die christliche kirche redet dort i...,und last die süße musica gantz n b freudenreic...
27,E000072,15,52,und last die süße musica gantz n b freudenreic...,zwingt die saiten in cithara/,so wird adam auff dem felde/
28,E000070,80,0,"so zwingt die säiten in cithara,",amen. demnach,und lasst die süsse musica gantz freudenreich ...
29,E000070,80,1,und lasst die süsse musica gantz freudenreich ...,"so zwingt die säiten in cithara,",singet/ klinget/ jubiliret/ triumphiret/
30,E000070,80,2,singet/ klinget/ jubiliret/ triumphiret/,und lasst die süsse musica gantz freudenreich ...,danckt dem herren/ groß ist der könig der ehren.
31,E000070,80,3,danckt dem herren/ groß ist der könig der ehren.,singet/ klinget/ jubiliret/ triumphiret/,si vox praeconis clara undique personat alto i...
32,E000068,45,0,"zwingt die seiten in cithara,",nun,zwingt die pfeiffen in organo und lasst die sü...
33,E000068,45,1,zwingt die pfeiffen in organo und lasst die sü...,"zwingt die seiten in cithara,",gantz freudenreich erschallen.
34,E000068,45,2,gantz freudenreich erschallen.,zwingt die pfeiffen in organo und lasst die sü...,alles/ was odem hat/
35,E000056,6,2,das eintzige gesäzz: zwingt die saiten in cith...,mit einander werden gesungen und geklungen haben/,der zu unserer orgel-weyhe erwehlte text/
36,E000104,20,2,zwingt doch die säyten in cithara/,und mit vollem munde ihn loben!,und last die schöne musica gantz freudenreich ...
37,E000104,20,3,und last die schöne musica gantz freudenreich ...,zwingt doch die säyten in cithara/,selbst die seraphinen gehen euch mit ihrem exe...
38,E000052,20,18,zwingt die säyten in cythara etc.,singet mit einstimmen unserer lobschallenden n...,und bethet darauf ein gläubiges und andächtige...
39,E000052,25,31,"zwingt die säyten in cithara,",amabimus &amp; laudabimus wir werden gott lieb...,und last die süsse musica gantz freudenreich e...
40,E000052,25,32,und last die süsse musica gantz freudenreich e...,"zwingt die säyten in cithara,",daß ich möge mit jesulein dem allerschönsten b...
41,E000052,25,33,daß ich möge mit jesulein dem allerschönsten b...,und last die süsse musica gantz freudenreich e...,"nimmermehr kan eine orgel so viel züge haben,"
42,E000061,13,0,herr gott vater mein starcker held etc.,wenn wir noch zuvor zur ermunterung unsrer and...,den 5. 6. und 7.
43,E000061,13,3,wie schön leuchtet der morgenstern.,v. aus dem liede:,das heutige heilige evangelium am 1.
44,E000042,34,0,"zwingt die saiten in cythara,","auch einander, also desto freudiger zuruffen.","und lasst die süsse musica,"
45,E000042,34,1,"und lasst die süsse musica,","zwingt die saiten in cythara,","ganz freudenreich erschallen, daß ich möge mit..."
46,E000042,34,2,"ganz freudenreich erschallen, daß ich möge mit...","und lasst die süsse musica,",jn steter liebe wallen!
47,E000042,34,3,jn steter liebe wallen!,"ganz freudenreich erschallen, daß ich möge mit...","singet, springet, jubiliret, triumphiret,"
48,E000042,34,4,"singet, springet, jubiliret, triumphiret,",jn steter liebe wallen!,"danckt dem herren, groß ist der könig der ehren."
49,E000042,34,5,"danckt dem herren, groß ist der könig der ehren.","singet, springet, jubiliret, triumphiret,",amen!
50,E000036,30,0,"zwingt die säiten in cithara,",mit eurer angenehmen music uns eine sabbathslu...,und laßt die süsse musica gantz freudenreich e...
51,E000036,30,1,und laßt die süsse musica gantz freudenreich e...,"zwingt die säiten in cithara,","daß ich möge mit jesulein,"
52,E000036,30,2,"daß ich möge mit jesulein,",und laßt die süsse musica gantz freudenreich e...,"dem wunderschönen bräutgam mein,"
53,E000036,30,3,"dem wunderschönen bräutgam mein,","daß ich möge mit jesulein,",jn steter liebe wallen.
54,E000036,30,4,jn steter liebe wallen.,"dem wunderschönen bräutgam mein,","singet, springet, jubiliret, triumphiret,"
55,E000036,30,5,"singet, springet, jubiliret, triumphiret,",jn steter liebe wallen.,"danckt dem herren, groß ist der könig der ehren!"
56,E000036,30,6,"danckt dem herren, groß ist der könig der ehren!","singet, springet, jubiliret, triumphiret,",und denn auch:
57,E000036,75,0,"singet, springet, jubiliret, triumphiret,",und die christliche kirche ihm nachsinget:,"danckt dem herren, groß ist der könig der ehren."
58,E000036,75,1,"danckt dem herren, groß ist der könig der ehren.","singet, springet, jubiliret, triumphiret,",s videsis dauderst. lab.

In [ ]:
def get_full_quotes(df):
    # Ensure proper order
    df = df.sort_values(["sermon","par","sent"]).reset_index(drop=True)

    # Detect breaks in consecutiveness *per sermon and par*
    df["break"] = (
        (df["sent"] != df["sent"].shift(1) + 1) | 
        (df["par"] != df["par"].shift(1)) |
        (df["sermon"] != df["sermon"].shift(1))
    )

    # Create group id
    df["grp"] = df["break"].cumsum()

    # Group and concatenate
    # aggregate while keeping sermon/par in output
    out = (
        df.groupby(["sermon","par","grp"], as_index=False)
        .agg(
            sent_min = ("sent","min"),
            sent_max = ("sent","max"),
            verse = ("verse", " ".join)
        )
    )

    # optional: pretty sent_range and drop grp
    out["sent_range"] = out.apply(
        lambda r: str(r["sent_min"]) if r["sent_min"]==r["sent_max"] else f"{r['sent_min']}-{r['sent_max']}",
        axis=1
    )
    out = out.drop(columns="grp")
    return out

In [162]:
def get_sent_before(id, par, sent):
    sermon = Sermon(id)
    if sent != 0:
        return " ".join(sermon.chunked[par][sent-1]["words"])
    else:
        return ""
def get_sent_after(id, par, sent):
    sermon = Sermon(id)
    if sent+1 != len(sermon.chunked[par]):
        return " ".join(sermon.chunked[par][sent+1]["words"])
    else:
        return ""

In [ ]:
full_quotes = get_full_quotes(results)
full_quotes["before"] = full_quotes.apply(
    lambda r: get_sent_before(r["sermon"], r["par"], r["sent_min"]), axis=1
)
full_quotes["after"] = full_quotes.apply(
    lambda r: get_sent_after(r["sermon"], r["par"], r["sent_max"]), axis=1
)
full_quotes

,sermon,par,sent_min,sent_max,verse,sent_range,before,after
0,E000036,30,0,6,"zwingt die säiten in cithara, und laßt die süs...",0-6,,
1,E000036,75,0,1,"singet, springet, jubiliret, triumphiret, danc...",0-1,,
2,E000042,34,0,5,"zwingt die saiten in cythara, und lasst die sü...",0-5,,amen!
3,E000052,20,18,18,zwingt die säyten in cythara etc.,18,singet mit einstimmen unserer lobschallenden n...,und bethet darauf ein gläubiges und andächtige...
4,E000052,25,31,33,"zwingt die säyten in cithara, und last die süs...",31-33,amabimus &amp; laudabimus wir werden gott lieb...,"nimmermehr kan eine orgel so viel züge haben,"
5,E000056,6,2,2,das eintzige gesäzz: zwingt die saiten in cith...,2,mit einander werden gesungen und geklungen haben/,
6,E000061,13,0,0,herr gott vater mein starcker held etc.,0,,den 5. 6. und 7.
7,E000061,13,3,3,wie schön leuchtet der morgenstern.,3,v. aus dem liede:,
8,E000068,45,0,2,"zwingt die seiten in cithara, zwingt die pfeif...",0-2,,
9,E000070,80,0,3,"so zwingt die säiten in cithara, und lasst die...",0-3,,
10,E000072,15,51,52,zwingt die saiten in cithara/ und last die süß...,51-52,43/32. und die christliche kirche redet dort i...,so wird adam auff dem felde/
11,E000075,15,0,3,so zwingt demnach die saiten in cithara/ und l...,0-3,,
12,E000079,26,44,46,zwingt die säiten in cithara/ und last die süs...,44-46,sollen wir doch dem herrn singen und spielen i...,oder die harpfen an die weide hengen/
13,E000083,20,0,4,zwingt die saiten in cythara/ und lasst die sü...,0-4,,
14,E000091,60,0,6,ey/ mein perle du werthe cron/ wahr gottes und...,0-6,,
15,E000091,61,0,6,zwingt die seiten in cythara/ vnd lasst die sü...,0-6,,
16,E000104,20,2,3,zwingt doch die säyten in cithara/ und last di...,2-3,und mit vollem munde ihn loben!,selbst die seraphinen gehen euch mit ihrem exe...

In [196]:
relevant_sermons

[['E000001', 'Christliche Predigt (Tübingen 1602)', 1602],
 ['E000002', 'Musica instrumentalis (Meißen 1605)', 1605],
 ['E000029', 'Christliche Predigt (Tübingen 1606)', 1606],
 ['E000030', 'Elogium Organi Musici (Altenburg 1610)', 1610],
 ['E000099', 'Corona Templi (Nürnberg 1621)', 1621],
 ['E000003', 'Vlmische Orgel Predigt (Ulm 1624)', 1624],
 ['E000098', 'Musica ecclesiastica (Stettin 1628)', 1628],
 ['E000096', 'Kostbare Bosische Orgel (Zwickau 1647)', 1647],
 ['E000095',
  'Längst=gewüntzschte Mittweidische Orgel=Freude (Dresden 1648)',
  1648],
 ['E000092', 'Organologismos (Dresden 1651)', 1651],
 ['E000091', 'Stolpenische Ehren-Crone (Dresden 1652)', 1652],
 ['E000090', 'Organolustria Evangelico-Stambachiana (Hof 1660)', 1660],
 ['E000089', 'Encoenia HierOrganica (Halle 1664)', 1664],
 ['E000086', 'Orgel=Predigt (Arnstadt 1666)', 1666],
 ['E000085', 'Das fröliche Hallelujah (Halle 1667)', 1667],
 ['E000083', 'Das Gott=Lob=Schallende Hosianna (Leipzig 1671)', 1671],
 ['E000082', 'Geistliches Orgelwerk (Erfurt 1672)', 1672],
 ['E000079', 'Denck- und Danck-Säule (Rothenburg ob der Tauber [1673])', 1673],
 ['E000078', 'Das fröliche Halleluja (Wittenberg 1675)', 1675],
 ['E000075',
  'Das Lieblich=klingende Orgeln und Saiten=Spiel (Coburg 1676)',
  1676],
 ['E000106', 'Die andere Predigt (Coburg 1676)', 1676],
 ['E000073',
  'Geistlich= und Gott wohlgefälliges Lob- und Danck-Opffer (Bayreuth 1680)',
  1680],
 ['E000072', 'Gott und Gnug (Meißen 1681)', 1681],
 ['E000070', 'Cithara Theologica (Schleusingen 1683)', 1683],
 ['E000108', 'Organi Laudes (Plauen 1685)', 1685],
 ['E000069', 'Organum Mysticum (Dresden 1686)', 1686],
 ['E000068', 'Das dem Allmächtigen abzustattende Lob (Altenburg s.a.)', 1687],
 ['E000067', 'Organo-Praxis Mystica (Görlitz 1689)', 1689],
 ['E000065', 'Eine Christliche Orgel=Predigt (Danzig 1695)', 1695],
 ['E000063', 'Schuldiges Lob Gottes (Nürnberg 1696)', 1696],
 ['E000060', 'Die Christliche Harmonie (Jena 1700)', 1700],
 ['E000058', 'Christliche Orgel-Predigt (Danzig s.a.)', 1704],
 ['E000059', 'Einweihungs-Predigt (Görlitz 1704)', 1704],
 ['E000056', 'Orgel Weih-Predigt (Ansbach 1709)', 1709],
 ['E000057',
  'Das rein-gestimmte Orgel-Werk unsers Herzens (Nürnberg s.a.)',
  1709],
 ['E000055', 'Davids Vermahnung (Dresden 1711)', 1711],
 ['E000104',
  'Evangelischer Christen Gott-gefällige Kirch-Weyhung (Dresden 1711)',
  1711],
 ['E000053', 'Vivum Dei Organum (Schneeberg s.a.)', 1720],
 ['E000051', 'Die Kneiphöffsche laute Orgel=Stimme (Königsberg 1721)', 1721],
 ['E000052', 'Ein wolgerührtes Orgel=Werck (Königsberg 1721)', 1721],
 ['E000074',
  'Glaubiger Kinder Gottes Gott=gefällige Music (Augsburg 1721)',
  1721],
 ['E000048', 'Die verstimmte Zwölff Grösseste Pfeiffen (Tübingen s.a.)', 1726],
 ['E000046',
  'Die edle und wohlgeordnete Music der Gläubigen (Halle 1727)',
  1727],
 ['E000045', 'Hymnosophia sacra (Billwerder 1728)', 1728],
 ['E000061', 'Einweihungs-Predigt (Berlin 1730)', 1730],
 ['E000042', 'Das Neue Lied (Freiberg 1735)', 1735],
 ['E000109', 'Stimme des Predigers (1737)', 1737],
 ['E000041', 'Die Billige Orgel-Freude (Danzig 1739)', 1739],
 ['E000039', 'Winnedisches Reminiscere (Stuttgart 1740)', 1740],
 ['E000038', 'Den rechtmäßigen Gebrauch der Music (Königsberg 1747)', 1747],
 ['E000036', 'Die heilige Sabbaths-Lust an dem Herrn (Danzig 1749)', 1749],
 ['E000037', 'Christliche Predigt (Straßburg 1749)', 1749],
 ['E000035', 'Musicalische Orgel= Lob= und Ehren=Predigt (s.l. 1751)', 1751],
 ['E000034', 'Lob= und Danck=Predigt (Berlin 1753)', 1753],
 ['E000027', 'Der Christen gerechte Freude (Breslau 1761)', 1761],
 ['E000024',
  'Die heiligen Verrichtungen in dem Hause des Herrn (Eisenach 1765)',
  1765],
 ['E000023', 'Der rechte Gebrauch der Orgeln (Altenburg 1766)', 1766],
 ['E000021', 'Das heilige und fröliche Aufsehen (Tübingen 1767)', 1767],
 ['E000020', 'Predigt am Feste der Heimsuchung Mariae (Rostock 1770)', 1770],
 ['E000016', 'Der Dienst der Orgeln (Jena 1778)', 1778],
 ['E000014', 'Gast-Predigt (Ulm 1781)', 1781],
 ['E000015',
  'Rede und Predigt bey Einweihung der neuen Orgel (Stockholm 1781)',
  1781],
 ['E000009', 'Predigt bey Einweyhung der Orgel (s.l. 1795)', 1795],
 ['E000008', 'Predigt Bey der Einweihung einer Orgel (Leipzig 1797)', 1797],
 ['E000007',
  'Predigt bey der feyerlichen Einweihung der neuen Orgel (Magdeburg 1798)',
  1798]]

In [164]:
def create_html(df):
    df["formatted"] = df.apply(
    lambda r: f'{r['before']} <span class="actual_quote">{r['verse']}</span>{r['after']}', axis=1
)
    sermon_dict = df.groupby("sermon")["formatted"].agg(list).to_dict()
    return sermon_dict

In [175]:
x = [{"key1": "val1"}, {"key2": "val2"}]
all_keys = []
for xx in x:
    y = [a for a,b in xx.items()]
    all_keys.extend(y)
all_keys

['key1', 'key2']

In [177]:
for elem in x:
    if "key1" in elem.keys():
        print(elem["key1"])

val1

In [179]:
[b["key1"] for b in x if "key1" in b.keys()]

['val1']

In [ ]:
with open("predigten_übersicht.json", "r", encoding="utf-8") as file: 
    data = json.load(file)

# Ensure all entries have a 'year' key
cleaned = {k: v for k, v in data.items() if 'year' in v}

year_finder = re.compile(r'[0-9]{4}')

for k, v in data.items():
    year = re.findall(year_finder, v['year'])[0]
    if year:
        v['year'] = year
    else:
        v['year'] = '[s.a.]'

# Convert to nested list and sort by year
relevant_sermons = sorted(
    [[key, value['title'], int(value['year'])] for key, value in cleaned.items()],
    key=lambda x: x[2]
)

ids = [x[0] for x in relevant_sermons]

source_options = []
for id in ids:
    sermon = Sermon(id)
    source_options.extend(set(flatten(sermon.reference)))

source_options = [x for x in source_options if is_id(x)]

id_counts = Counter(source_options)

In [194]:
# Sort IDs by frequency descending
sorted_ids = [[item[0], item[1]] for item in id_counts.most_common()]
options = [{f'{get_short_info(i[0])} ({i[1]} Verweise)' :i[0]} for i in sorted_ids]
keys = []
for x in options:
    key = [key for key, val in x.items()]
    keys.extend(key)

In [195]:
keys

['Praetorius, Michael: Syntagmatis Musici Michaelis Praetorii C. Tomus Secundus De Organographia (1619) (22 Verweise)',
 'anonym: In dulci jubilo (16 Verweise)',
 'Gratianus de Clusio: Decretum Gratiani emendatum & notationibus illustratum, una cum glossis (1604) (14 Verweise)',
 'Nicolai, Philipp: Wie schön leuchtet der Morgenstern (13 Verweise)',
 'Augustinus, Aurelius ; Thimme, Wilhelm (Übers.): Confessiones. Bekenntnisse (2004) (12 Verweise)',
 'Anonym: Ach Gott wie manches Herzeleid (12 Verweise)',
 'Conrad Dieterich, 1575/01/09 (Gemünden (Wohra))-1639/03/22 (Ulm): Vlmische Orgel Predigt (Ulm 1624) (11 Verweise)',
 'Zwinger, Theodor: Theatrvm Hvmanae Vitae Theodori Zuingeri Bas[isliensis] Tertiatione ([1586]) (8 Verweise)',
 'N.N.: Herr Gott, dich loben wir (8 Verweise)',
 'Crüger, Johann: Sei Lob und Ehr dem höchsten Gut (8 Verweise)',
 'Luther, Martin: D. Martin Luthers Werke (1969) (7 Verweise)',
 'Augustinus, Aurelius ; Gori, Franco (Hrsg.): Enarrationes in psalmos\xa0101–150 (2005) (7 Verweise)',
 'Luther, Martin ; Aurifaber, Johannes (Hrsg.): Colloquia, Oder, Christliche, nützliche Tischreden Doctoris Martini Lutheri (1591) (7 Verweise)',
 'Luther, Martin ; Sagittarius, Johann Christfried (Hrsg.): Der Achte Teil aller teutschen Bücher und Schrifften des theuren seeligen Mannes Gottes/ Doct. Martini Lutheri (1662) (7 Verweise)',
 'Crüger, Johann (Rinckart, Martin): Nun danket alle Gott, 1636 (7 Verweise)',
 'anonym: Herr Jesu Christ, dich zu uns wend (7 Verweise)',
 'Geier, Martin: Commentarius in Psalmos Davidis (1681) (7 Verweise)',
 'Hospinianus, Rodolphus: De origine, progressu, usu et abusu templorum ac rerum omnium (1587) (6 Verweise)',
 'Luther, Martin: Aus tiefer Not schrei ich zu dir (6 Verweise)',
 'Platina, Bartholomaeus: B. Platinae Cremonensis De Vita &amp; moribus summorum Pontificum historia (1529) (6 Verweise)',
 'Speratus, Paulus: Es ist das Heil uns kommen her (6 Verweise)',
 'Luther, Martin: Nun freut euch, lieben Christen gmein. Ein Christenlichs lied Doctoris Martini Luthers/ die vnaussprechliche gnaden Gottes vnd des rechten Glaubens begreyffendt (1523) (6 Verweise)',
 'Praetorius, Michael: Syntagmatis Musici Michaelis Praetorii C. Tomus Primus (1615) (6 Verweise)',
 'Dachstein, Wolfgang: An Wasserflüssen Babylon (6 Verweise)',
 'anonym: Herzlich tut mich erfreuen (6 Verweise)',
 'Polydorus, Vergilius: De rerum inventoribus (1532) (6 Verweise)',
 'anonym: Wir glauben all an einen Gott (6 Verweise)',
 'Kircher, Athanasius: Musurgia universalis, sive ars magna consoni et dissoni (1650) (6 Verweise)',
 'Augustinus, Aurelius: S. Avrelii Avgvstini Hipponensis Episcopi Opera Qvae Reperiri Potvervnt Omnia (1616) (6 Verweise)',
 'Augustinus, Aurelius: D. Avrelii Avgvstini Hipponensis Episcopi, Confessionum Libri tredecim (1581) (6 Verweise)',
 'Aventinus, Johannes ; \tCisnerus, Nikolaus (Hrsg.): Io. Aventini Annalivm Boiorvm Libri VII (1580) (5 Verweise)',
 'Bale, John: Acta romanorum Pontificum (1558) (5 Verweise)',
 'Flavius Josephus ; Gelen, Sigmund (Hrsg.) ; Erasmus, Desiderius (Hrsg.): Flavii Iosephi Antiqvitatvm Ivdaicarvm Libri XX (1559) (5 Verweise)',
 'Turmair, Johannes (Aventinus): Annales ducum Boiariae (1881) (5 Verweise)',
 'Kugelmann, Hans: Nun lob, mein Seel, den Herren (5 Verweise)',
 'Luther, Martin: Ein feste Burg ist unser Gott (5 Verweise)',
 'Luther, Martin: Der Sechste Teil aller Buecher vnd Schrifften/ des thewren seligen Mans Gottes/ Doctoris Martini Lutheri (1568) (5 Verweise)',
 'Walter, Johann: Es woll uns Gott genädig sein (5 Verweise)',
 'Anonym: Kommt her zu mir, spricht Gottes Sohn (5 Verweise)',
 'Bakius, Reinhard: Commentarius Exegetico-Practicus Posthumus, In Psalterium Davidis (1664) (5 Verweise)',
 'anonym (nach Hans Sachs): Wachet auf, ruft uns die Stimme (5 Verweise)',
 'Herman, Nikolaus: Wenn mein Stündlein vorhanden ist (1562) (5 Verweise)',
 'Großgebauer, Theophil: Drey Geistreiche Schrifften (1682) (5 Verweise)',
 'Mayer, Johann Friedrich: Museum Ministri Ecclesiae (1690) (5 Verweise)',
 'Calvör, Caspar: Ritvalis Ecclesiastici Pars Altera (1705) (5 Verweise)',
 'Plinius Caecilius Secundus, Gaius ; Kasten, Helmut (Hrsg. und Übersetzer): Briefe (1995) (4 Verweise)',
 'Clemens von Alexandria ; Hervet, Gentian (Hrsg.): Clementis Alexandrini [...] omnia quae quidem extant opera (1572) (4 Verweise)',
 'Herberger, Valerius: HertzPostilla Valerii Herbergeri (1613) (4 Verweise)',
 'Theodoretus: Beati Theodoreti Episcopi Cyrensis [...] opera omnia, quae ad hunc diem Latine versa sparsim extiterunt (1617) (4 Verweise)',
 'Mengering, Arnold: Informatorium Conscientiae Evangelicum (1644) (4 Verweise)',
 'Walter, Johann: Erbarm dich mein O Herre Gott (4 Verweise)',
 'Beyerlinck, Laurens: Magnvm Theatrvm Vitæ Hvmanæ: Hoc Est Rervm Divinarvm, Hvmanarvmqve Syntagma Catholicvm, Philosophicvm, Historicvm, Et Dogmaticvm Ad normam Polyantheæ vniuersalis dispositum (1665) (4 Verweise)',
 'Luther, Martin: Vater unser im Himmelreich (4 Verweise)',
 'Mithob, Hector: Psalmodia Christiana (1665) (4 Verweise)',
 'Voetius, Gisbert: Politicae ecclesiasticae Partis primae Libri duo priores (1663) (4 Verweise)',
 'Polydorus, Vergilius: De rerum inventoribus (1671) (4 Verweise)',
 'Sabellicus, Marcus Antonius: Rapsodiae historiarum Enneadum Marci Antonii Coccii Sabellici (1528) (4 Verweise)',
 'Pfeiffer, August: Dubia Vexata Scripturae Sacrae (1679) (4 Verweise)',
 'Lund, Johann: Die Alten Jüdischen Heiligthümer/ Gottes=dienste und Gewohnheiten (1701) (4 Verweise)',
 'Schop, Johann: Werde munter, mein Gemüte (4 Verweise)',
 "Nicolai, Philipp: Halleluja! Lob, Preis und Ehr' sei unserm Gott je mehr und mehr (4 Verweise)",
 'Flavius Josephus ; Erasmus, Desiderius (Hrsg.): Antiquitates Iudaicae Libri XX (1540) (3 Verweise)',
 'Horatius Flaccus, Quintus ; Färber, Hans (Übersetzer): Sämtliche Werke (1982) (3 Verweise)',
 'Justinus Martyr: Divi Ivstini, Philosophi Ac Martyris Opera (1555) (3 Verweise)',
 'Alberus, Erasmus: Wider die verfluchte Lere der Carlstader und alle fürnemste Heubter der Sacramentirer Rottengeister Widerteuffer Sacramentlesterer Eheschender Musica Verechter Bildstürmer Feiertagfeinde und Verwüster aller guten Ordnung (1565) (3 Verweise)',
 'Cicero, Marcus Tullius ; Gigon, Olof (Hrsg.): Gespräche in Tusculum (1992) (3 Verweise)',
 'Augustinus, Aurelius ; Migne, Jacques Paul (Hrsg.): Sancti Aurelii Augustini, Hipponensis episcopi, opera omnia (1841) (3 Verweise)',
 'Christoph Frick, 1577 (Burgdorf)-1640/04/09 (): Musica Christiana (Leipzig 1615) (3 Verweise)',
 'Rosinus, Johannes ; Dempster, Thomas (Hrsg.): Antiquitatum Romanarum corpus absolutissimum (1613) (3 Verweise)',
 'Andreä, Jacob ; Bèze, Théodore de: Acta Colloquij Montis Belligartensis (1587) (3 Verweise)',
 'Sachs, Michael: Newe KeyserChronica ([1643]) (3 Verweise)',
 'Azpilcueta, Martín de: Enchiridion sive manuale de oratione et horis caononicis (1578) (3 Verweise)',
 'Conrad Dieterich, 1575/01/09 (Gemünden (Wohra))-1639/03/22 (Ulm): Kirchweih= oder Orgel=Predigt (Leipzig 1632) (3 Verweise)',
 'N.N.: O Jesu Christ, meins Lebens Licht (3 Verweise)',
 'Augustinus, Aurelius ; Bernhardus ; Sommalius, Henricus (Hrsg.): Divi Aurelii Augustini Hippon. Episcopi Meditationes, Soliloquia et Manuale (1631) (3 Verweise)',
 'Dieterich, Conrad: Sonderbarer Predigten von vnterschiedenen Materien/ Hiebevor zu Vlm im Münster gehalten/ deren theils in Truck allbereit außgangen Theils aber ietzo von newem in Truck geben/ Erster Theil (1632) (3 Verweise)',
 'Decius, Nikolaus: Allein Gott in der Höh sei Ehr (3 Verweise)',
 'anonym: Ich ruf zu dir, Herr Jesu Christ (1526/1527) (3 Verweise)',
 'Eusebius Caesariensis: Ecclesiastica Historia (1611) (3 Verweise)',
 'Gottfried Siegmund Peisker, 1617/12/27 (Merseburg)-1678/10/01 (Zwickau): Stolpenische Ehren-Crone (Dresden 1652) (3 Verweise)',
 'Augustinus, Aurelius: S. Aur. Augustini Hipponensis Episcopi Opera Omnia (1837) (3 Verweise)',
 'Scotus, Marianus: Mariani Scoti chronica (1559) (3 Verweise)',
 'Johann Ludwig Hartmann, 1640/02/03 (Rothenburg ob der Tauber)-1684/07/18 (Rothenburg ob der Tauber): Denck- und Danck-Säule (Rothenburg ob der Tauber [1673]) (3 Verweise)',
 'Geier, Martin: Die köstlichste Arbeit/ aus dem 119. Psalm v. 54. Deine Rechte sind mein Lied in meinem Hause (1672) (3 Verweise)',
 'Crüger, Johann: Jesu, meine Freude (3 Verweise)',
 'Francisci, Erasmus: Die lustige Schau-Bühne von allerhand Curiositäten (1663) (3 Verweise)',
 'Schweizer, Johann Caspar: Thesaurus ecclesiasticus (1682) (3 Verweise)',
 'Isidorus Pelusiota ; Billy, Jacques de (Hrsg.): Epistolarum amplius mille ducentarum libri tres (1585) (3 Verweise)',
 'Picinelli, Filippo: Mundus Symbolicus (1681) (3 Verweise)',
 'Hospinianus, Rodolphus: De Templis Hoc Est, De Origine, Progressv, Vsv Et Abvsv Templorum (1672) (3 Verweise)',
 'Prudentius Clemens, Aurelius: Apotheosis (1876) (3 Verweise)',
 'Diruta, Girolamo: Il Transilvano (1969) (3 Verweise)',
 'Hospinianus, Rodolphus: De templis: hoc est, de origine, progressu, usu et abusu templorum, ac omnino rerum omnium ad templa pertinentium (1603) (3 Verweise)',
 'Augustinus, Aurelius ; Coqueau, Léonard (Hrsg.) ; Vives, Juan Luis (Hrsg.): De Civitate Dei, Libri XXII (1616) (3 Verweise)',
 'Lightfoot, John ; Carpzov, Johann Benedict (Hrsg.): Horae Hebraicae et Talmudicae In Qvatuor Evangelistas (1675) (3 Verweise)',
 'Dedeken, Georg: Thesauri Consiliorum et Decisionum Volumen Primum, Ecclesiastica continens (1671) (3 Verweise)',
 'Anton, Christoph ; Hintze, Jacob: Alle Menschen müssen sterben (3 Verweise)',
 'Calvör, Caspar: De Musica ac sigillatim de ecclesiastica eoque Spectantibus Organis (1702) (3 Verweise)',
 'Arnold, Gottfried: Die Erste Liebe Der Gemeinen Jesu Christi (1696) (3 Verweise)',
 'Nicephorus Callistus ; Lange, Johannes (Hrsg. u. Übers.): Nicephori Callisti Xanthopuli, Scriptoris Vere Catholici, Ecclesiasticae Historiae Libri Decem Et Octo (1588) (2 Verweise)',
 'Schickhardt, Heinrich: Beschreibung Einer Raiß, Welche der Durchleuchtig Hochgeborne Fürst vnd Herr, Herr Friderich Hertzog zu Württemberg vnnd Teckh [...]  Im Jahr, 1599. selbs Neundt, auß dem Landt zu Württemberg in Italiam gethan (1603) (2 Verweise)',
 'Hieronymus, Sophronius Eusebius ; Migne, Jacques Paul (Hrsg.): Sancti Eusebii Hieronymi Stridonensis Presbyteri epistolae (1845) (2 Verweise)',
 'Prediger im Fürstenthumb Anhalt: Erinnerungs Schrifft etlicher vom Adel vnd Stedten An den Durchleuchtigen Hochgebornen Fuersten vnd Herrn Herrn Johann Georgen Fuersten zu Anhalt Graffen zu Ascanien HErrn zu Zerbst vnd Bernburg etc. (1596) (2 Verweise)',
 'Cicero, Marcus Tullius ; Nickel, Rainer (Hrsg.): De legibus. Paradoxa stoicorum (1994) (2 Verweise)',
 'Vitruvius ; Rode, August (Hrsg.): Marci Vitruvii Pollionis De architectura libri decem (1800) (2 Verweise)',
 'Schweigger, Salomon: Ein newe Reyßbeschreibung auß Teutschland Nach Constantinopel und Jerusalem (1608) (2 Verweise)',
 'Basilius Caesariensis: Divi Basilii Magni Archiepiscopi Caesareae Cappadociae Omnia, qvae ad nos extant Opera (1566) (2 Verweise)',
 'Lactantius, Lucius Coelius Firmianus: L[ucii] Coelii Lactantii Firmiani Diuinarum institutionum Libri VII. (1521) (2 Verweise)',
 'Luther, Martin: Mit Fried und Freud ich fahr dahin (2 Verweise)',
 'Dieterich, Conrad: Poenitentialia Davidica (1624) (2 Verweise)',
 'Luther, Martin: Biblia: das ist: Die gantze Heilige Schrifft (1541) (2 Verweise)',
 'Spangenberg, Cyriacus: Cithara Lutheri (1581) (2 Verweise)',
 'anonym: Christ ist erstanden (2 Verweise)',
 'Lang, Joseph: Loci Commvnes sive Florilegium Rerum Et Materiarum Selectarum (1598) (2 Verweise)',
 'Anonym: Allein zu dir Herr Jesu Christ (2 Verweise)',
 'Senfl, Ludwig: Non moriar sed vivam (M 066) (2 Verweise)',
 'Naso, Publius Ovidius ; Willige, Wilhelm (Übers.) ; Holzberg, Niklas (Hrsg.): Briefe aus der Verbannung (2001) (2 Verweise)',
 'Luther, Martin: Der Fünffte Teil/ aller Buecher vnd Schrifften/ des thewren seligen Mans Gottes Docto[ris] Martini Lutheri (1575/1577) (2 Verweise)',
 'anonym: Veni, Sancte Spiritus (2 Verweise)',
 'Buxtorf, Johann: Lexicon Hebraicum Et Chaldaicum (1615) (2 Verweise)',
 'Gesner, Salomon: Commentationes In Psalmos Davidis (1629) (2 Verweise)',
 'Luther, Martin: Der Achte Teil vnd letzte aller Buecher vnd schrifften des thewren seligen Mans Gottes/ Doctoris Martini Lutheri (1568) (2 Verweise)',
 'Plinius Secundus, Gaius ; Gelenius, Sigismundus (Hrsg.) ; Manuzio, Paolo (Hrsg.): G. Plinii Secundi Naturalis Historiae Libri 37 (1559) (2 Verweise)',
 'Theophylactus ; Ökolampadius, Johannes (Übers.): Theophylacti Archiepiscopi Bvlgariae, in quatuor Euangelia enarrationes (1524) (2 Verweise)',
 'Augustinus, Aurelius: Enchiridion Ad Laurentium Urbis Romae Primicerium (1604) (2 Verweise)',
 'Hieronymus Stridoniensis ; Victorius, Marianus (Hrsg.): Sancti Hieronymi Stridoniensis Opera Omnia, Quae Extant (1616) (2 Verweise)',
 'Luther, Martin ; Sagittarius, Johann Christfried (Hrsg.): Der Neunte Teil aller teutschen Bücher und Schrifften des theuren seeligen Mannes Gottes/ Doct. Martini Lutheri (1663) (2 Verweise)',
 'N.N.: Gott sei uns gnädig und barmherzig (2 Verweise)',
 'Pagnini, Sante ; Mercier, Jean: Thesavrvs Lingvae Sanctae, Sive, Lexicon Hebraicvm (1577) (2 Verweise)',
 'Schütz, Heinrich: Lobt Gott in seinem Heiligthum (2 Verweise)',
 'Kromayer, Hieronymus: Ecclesia In Politia Id est Historiae Ecclesiasticae Centuriae XVI (1666) (2 Verweise)',
 'N.N.: Wach auf mein Herz und singe (2 Verweise)',
 'Vergilius Maro, Publius ; Taubmann, Friedrich (Hrsg.): Culex/ Augusto Caesari olim dicatus (1609) (2 Verweise)',
 'Luther, Martin: Enchiridion (1601) (2 Verweise)',
 'Anonym: Komm, Heiliger Geist, Herre Gott (2 Verweise)',
 'Albrecht, Georg ; Albrecht, Bernhard (Hrsg.): Volumen Concionum Miscellanearum (1653) (2 Verweise)',
 'anonym: Österreichisches Jammer=Lied (2 Verweise)',
 'Mengering, Arnold: Scrutinium Conscientiae Catecheticum (1642) (2 Verweise)',
 'Vermigli, Pietro Martire: Loci Communes D. Petri Martyris Vermilii Florentini (1622) (2 Verweise)',
 'anonym: Warum betrübst du dich, mein Herz (2 Verweise)',
 'Bona, Giovanni: De divina psalmodia, eiusque causis, mysteriis et disciplinis (1663) (2 Verweise)',
 'Titius, Caspar: Loci theologici historici, oder theologisches Exempel-Buch (1657) (2 Verweise)',
 'N.N.: Wenn wird doch mein Jesus kommen (2 Verweise)',
 'Luther, Martin ; Sagittarius, Johann Christfried (Hrsg.): Der Ander Teil aller teutschen Bücher und Schrifften des theuren seeligen Mannes Gottes/ Doct. Martini Lutheri (1661) (2 Verweise)',
 'Walter, Johann: Mitten wir im Leben sind mit dem Tod umfangen (2 Verweise)',
 'Engelgrave, Henricus: Lvx Evangelica sub velum Sacrorvm Emblematvm Recondita (1655) (2 Verweise)',
 'N.N.: Von Gott will ich nicht lassen (2 Verweise)',
 'Hieronymus, Sophronius Eusebius ; Migne, Jacques Paul (Hrsg.): Sancti Eusebii Hieronymi Stridonensis Presbyteri, Commentariorum in Epistolam ad Ephesios libri tres (1845) (2 Verweise)',
 'Plutarch ; Volkmann, Richard: Plutarchi De musica (1856) (2 Verweise)',
 'Dannhauer, Johann Conrad: Catechismus Milch Oder Der Erklärung deß Christlichen Catechismi (1666) (2 Verweise)',
 'Luther, Martin ; Sagittarius, Johann Christfried (Hrsg.): Der Sechste Teil aller teutschen Bücher und Schrifften des theuren seeligen Mannes Gottes/ Doct. Martini Lutheri (1662) (2 Verweise)',
 'Quenstedt, Johann Andreas: Theologia Didactico-Polemica, Sive Systema Theologicum, In Duas Sectiones, Didacticam Et Polemicam, Divisum (1691) (2 Verweise)',
 'Luther, Martin: Erhalt uns, Herr, bei deinem Wort (2 Verweise)',
 'Luther, Martin ; Sagittarius, Johann Christfried (Hrsg.): Der Fünffte Teil aller teutschen Bücher und Schrifften des theuren seeligen Mannes Gottes/ Doct. Martini Lutheri (1662) (2 Verweise)',
 'Luther, Martin: D. Martin Luthers Werke (1912 (Reprint 19) (2 Verweise)',
 'Dieterich, Johann Conrad ; Pistorius, Johann Justus (Hrsg.): Antiquitates Biblicae (1671) (2 Verweise)',
 'Casali, Giovanni Battista: De profanis et sacris veteribus ritibus (1681) (2 Verweise)',
 'Zonaras, Johannes: Ioannis Zonarae Monachi [...] compendium Historiarum (1557) (2 Verweise)',
 "Alberti, Leandro: Descrittione di tutta Italia, nella quale si contiene il sito di essa, l'origine, et le signorie delle cità, & delle castella, co i nomi antichi, & moderni, i costumi de popoli, le conditioni de Paesi (1551) (2 Verweise)",
 'Calvin, Jean: Opera quae supersunt omnia (1889) (2 Verweise)',
 'Lavater, Ludwig: Nehemias (1586) (2 Verweise)',
 'Heidenreich, Tobias: Leipzigische Cronicke/ Und zum Theil Historische Beschreibung der fürnehmen/ und weitberühmbten Stadt Leipzig ([1635]) (2 Verweise)',
 'Maiolo, Simeone: Dies Canicvlares (1607) (2 Verweise)',
 'Weber, Johann Adam: Ars Discurrendi De Qualibet Materia (1673) (2 Verweise)',
 'Durantis, Guilelmus: Rationale Divinorum Officiorum (1599) (2 Verweise)',
 'Aimonus Floriacensis: Historiae Francorum libri quinque (1567) (2 Verweise)',
 'Olearius, Johannes: Biblischer Erklärung Dritter Theil (1679) (2 Verweise)',
 'Schelwig, Samuel: Cynosura Conscientiae, Oder Leit-Stern Des Gewissens (1692) (2 Verweise)',
 'Isidorus Hispalensis ; La Bigne, Marguerin de (Hrsg.): Sancti Isidori Hispalensis episcopi, opera omnia quae extant, partim aliquando virorum doctissimorum laboribus edita (1580) (2 Verweise)',
 'Lubin, Eilhard (Hrsg.): Anthologia Diaphorōn Epigrammatōn Palaiōn eis hepta biblia diērēmenē (1603) (2 Verweise)',
 'Poole, Matthew: Synopsis criticorum aliorumque S. Scripturæ interpretum (1678) (2 Verweise)',
 'Vossius, Gerhardus Johannes: De Qvatuor Artibvs Popvlaribvs, De Philologia, Et Scientiis Mathematicis Libri Tres (1650) (2 Verweise)',
 'Panciroli, Guido: Guidonis Pancirolli Rerum Memorabilium sive Deperditarum Pars Prior (1629) (2 Verweise)',
 'Camerarius, Philipp: Operae Horarvm Svbcisivarvm, Sive Meditationes Historicae, Avctiores qvam antea editae (1601) (2 Verweise)',
 'Augustinus, Aurelius: Tomvs VIII. Opervm D. Avrelii Avgvstini Hipponensis Episcopi (1569) (2 Verweise)',
 'Gerber, Christian: Unerkannte Sünden der Welt/ sambt einem Bericht/ von den Sünden der Menschen nach ihren Todte (1699) (2 Verweise)',
 'Scriver, Christian: Seelen=Schatzes Vierdter Theil (1687) (2 Verweise)',
 'Chemnitz, Martin ; Leyser, Polycarp: Harmonia Quatuor Evangelistarum / A Theologis Celeberrimis, D. Martino Chemnitio Primum Inchoata: D. Polycarpo Lysero Post Continuata: Atque D. Johanne Gerhardo tandem felicissime absoluta (1652) (2 Verweise)',
 'Morhof, Daniel Georg: Danielis Georgi[i] Morhofi[i], Stentor Yaloklastēs sive de Scypho vitreo per certum humanae vocis sonum fracto ad V. Cl. Dn. Johannem Danielem Maiorem, Professorem Medicum [...] Dissertatio (1683) (2 Verweise)',
 'Happel, Eberhard Werner: E. G. Happelii grössester Denkwürdigkeiten der Welt oder so genandte Relationes Curiosae (1685) (2 Verweise)',
 'Gerhard, Johann: Harmonia Quatuor Evangelistarum (1652) (2 Verweise)',
 'Bona, Giovanni: Rerum Liturgicarum Libri Duo (1674) (2 Verweise)',
 'Luther, Martin: Nimm von uns, Herr, du treuer Gott (2 Verweise)',
 'Luther, Martin: Es ist gewisslich an der Zeit (2 Verweise)',
 'Loescher, Caspar ; Pipping, Heinrich: Dissertatio Historico-Theologica, De Saule Per Musicam Curato (1688) (2 Verweise)',
 'N.N.: Treuer Gott ich muß dir klagen (2 Verweise)',
 'Glaß, Salomon: Philologiae Sacrae, Qua Totius Sacrosanctae, Veteris & Novi Testamenti, Scripturae, Tum Stylus Et Literatura, Tum Sensus Et Genuinae Interpretationis Ratio Expenditur; Libri Quinque (1686) (2 Verweise)',
 'Taddel, Elias: Diatribe Theologico-Exegetica, quâ Preces Regis Chiskiæ Moribundi Ex Esaiæ XXXVIII. Cap. Com. X. & seqv. perspicue explicantur, ex integro Contextu declarantur, ac perpetua quadam Meditatione illustrantur (1704) (2 Verweise)',
 'Mirus, Adam Erdmann: Kurtze Fragen aus der Musica Sacra (1707) (2 Verweise)',
 'Olearius, Johann Christoph: Evangelischer Lieder-Schatz (1707) (2 Verweise)',

In [165]:
create_html(full_quotes)

{'E000036': [' <span class="actual_quote">zwingt die säiten in cithara, und laßt die süsse musica gantz freudenreich erschallen, daß ich möge mit jesulein, dem wunderschönen bräutgam mein, jn steter liebe wallen. singet, springet, jubiliret, triumphiret, danckt dem herren, groß ist der könig der ehren!</span>',
  ' <span class="actual_quote">singet, springet, jubiliret, triumphiret, danckt dem herren, groß ist der könig der ehren.</span>'],
 'E000042': [' <span class="actual_quote">zwingt die saiten in cythara, und lasst die süsse musica, ganz freudenreich erschallen, daß ich möge mit jesulein dem wunderschönen bräutgam mein, jn steter liebe wallen! singet, springet, jubiliret, triumphiret, danckt dem herren, groß ist der könig der ehren.</span>amen!'],
 'E000052': ['singet mit einstimmen unserer lobschallenden neuen orgel: <span class="actual_quote">zwingt die säyten in cythara etc.</span>und bethet darauf ein gläubiges und andächtiges vater unser',
  'amabimus &amp; laudabimus wir werden gott lieben und loben und der bekandte kirchengesang führet die liebe jesu als eine würckung der instrumental-musique an: <span class="actual_quote">zwingt die säyten in cithara, und last die süsse musica gantz freudenreich erschallen; daß ich möge mit jesulein dem allerschönsten bräutgam mein in steter liebe wallen.</span>nimmermehr kan eine orgel so viel züge haben,'],
 'E000056': ['mit einander werden gesungen und geklungen haben/ <span class="actual_quote">das eintzige gesäzz: zwingt die saiten in cithara etc.</span>'],
 'E000061': [' <span class="actual_quote">herr gott vater mein starcker held etc.</span>den 5. 6. und 7.',
  'v. aus dem liede: <span class="actual_quote">wie schön leuchtet der morgenstern.</span>'],
 'E000068': [' <span class="actual_quote">zwingt die seiten in cithara, zwingt die pfeiffen in organo und lasst die süsse musica, gantz freudenreich erschallen.</span>'],
 'E000070': [' <span class="actual_quote">so zwingt die säiten in cithara, und lasst die süsse musica gantz freudenreich erschallen; singet/ klinget/ jubiliret/ triumphiret/ danckt dem herren/ groß ist der könig der ehren.</span>'],
 'E000072': ['43/32. und die christliche kirche redet dort ihre gespielinnen an: <span class="actual_quote">zwingt die saiten in cithara/ und last die süße musica gantz n b freudenreich erschallen.</span>so wird adam auff dem felde/'],
 'E000075': [' <span class="actual_quote">so zwingt demnach die saiten in cithara/ und laßt die süße musica gantz freudenreich erschallen; singet/ klinget/ jubiliret/ triumphiret/ danckt dem herren/ groß ist der könig der ehren!</span>'],
 'E000079': ['sollen wir doch dem herrn singen und spielen in unsern hertzen. <span class="actual_quote">zwingt die säiten in cithara/ und last die süsse musica/ gantz freudenreich erschallen. müssen wir schon manchmal in dieser welt weinen und heulen/</span>oder die harpfen an die weide hengen/'],
 'E000083': [' <span class="actual_quote">zwingt die saiten in cythara/ und lasst die süsse musica gantz freudenreich erschallen. singet/ springet/ jubiliret/ triumphiret/ danckt dem herren/ groß ist der könig der ehren/ amen.</span>'],
 'E000091': [' <span class="actual_quote">ey/ mein perle du werthe cron/ wahr gottes und marien sohn/ ein hochgeborner könig/ mein hertz heisst dich ein lilium/ dein süsses evangelium/ ist lauter milch und honig: ey mein/ blümlein/ hosianna/ himlisch manna/ daß wir essen/ deiner kan ich nicht vergessen.</span>',
  ' <span class="actual_quote">zwingt die seiten in cythara/ vnd lasst die süsse musica/ ganz freudenreich erschallen/ daß ich möge mit jesulein/ den allerhöchsten bräutgam mein/ jn steter liebe wallen/ singet/ springet/ jubiliret/ triumphiret/ danckt dem herrn/ groß ist der könig der ehren.</span>'],
 'E000104': ['und mit vollem munde ihn loben! <span class="actual_quote">zwingt doch die säyten in cithara/ und last die schöne musica gantz freudenreich erschallen!</span>selbst die seraphinen gehen euch mit ihrem exempel vor/']}

In [74]:
def get_closest_verse(sermon_line: str, source: list) -> list:
    best_match = ""
    best_score = 0
    for verse in source:
        sim_score = fuzz.ratio(sermon_line, verse.lower())
        if sim_score > best_score:
            best_score = sim_score
            best_match = verse
    
    return [best_match, best_score, source.index(best_match)]

In [75]:
results[["best_match", "sim_score", "line"]] = results["verse"].apply(lambda x: pd.Series(get_closest_verse(x, dieterich_verses)))

In [76]:
results

,sermon,verse,text_before,text_after,best_match,sim_score,line
0,E000091,mit hertzlicher dancksagung; denn nechst reine...,"1. deo pro organo gratias agendo,",wie auch rechter ausspendung der heiligen sacr...,mit welchen man den herrn in seinem heyligtumb...,52.941176,276
1,E000091,wie auch rechter ausspendung der heiligen sacr...,mit hertzlicher dancksagung; denn nechst reine...,"und einer guten vocal-music,",vnnd rechtem gebrauch/ der hochwürdigen sacram...,62.264151,1227
2,E000091,"und einer guten vocal-music,",wie auch rechter ausspendung der heiligen sacr...,sind die orgeln in kirchen eine sonderliche zi...,weder orgel noch music:,54.901961,1308
3,E000091,sind die orgeln in kirchen eine sonderliche zi...,"und einer guten vocal-music,",als dadurch nicht nur der öffentliche gottesdi...,vnd denen orgeln/ in der kirchen gottes/,59.340659,908
4,E000091,als dadurch nicht nur der öffentliche gottesdi...,sind die orgeln in kirchen eine sonderliche zi...,und ansehnlich gemachet wird/,sondern auch der offene gottesdienst in der ki...,64.285714,1233
...,...,...,...,...,...,...,...
318,E000074,oder wasserorgeln/ so durch wasser gestimmet w...,man hat auch hydraulica gehabt/,allein constantini pipino verehrte orgelpfeiff...,so durch wasser gestimmet worden/,75.294118,702
319,E000074,von welcher zeit an die orgeln in teutschland ...,ebenfalls von dem griechischen kayser constant...,daß fast keine vornehme kirch in städten/,die orgel inn den teutschen kirchen allgemach ...,63.492063,733
320,E000074,daß fast keine vornehme kirch in städten/,von welcher zeit an die orgeln in teutschland ...,flecken/ dörffern und clöstern gewesen/,daß fast kein vornehme kirch in stätten/,96.296296,734
321,E000074,flecken/ dörffern und clöstern gewesen/,daß fast keine vornehme kirch in städten/,welche nicht ein orgelwerck gehabt hätte.,welches ein recht gewesen/,55.384615,378
322,E000041,sondern rühre mit dem finger an deiner rechten...,so laß sich doch nicht allein die augen und oh...,gott dem werthen heiligen geist auch ihre hert...,sondern stürmen sie eintweder auß den kirchen ...,64.761905,965

In [77]:
quoting_sermons = results['sermon'].values.tolist()

In [78]:
x = results.loc[results["best_match"] == "Singet springet Jubilieret triumphieret /"].values.tolist()[0]

IndexError: list index out of range

In [79]:
lines_with_data = []
for line in dieterich_verses:
    row_list = results.loc[results["best_match"] == line].values.tolist()
    lines_with_data.append({"name": line, "value":row_list})

lines_with_data

[{'name': 'vlmische orgel predigt/ darinn von der jnstrumentalmusic inns gemein/',
  'value': []},
 {'name': 'sonderlich aber von dero orgeln erfindung vnd gebrauch/',
  'value': []},
 {'name': 'in der kirchen gottes/',
  'value': [['E000090',
    'sind das wort gottes/',
    'die bälge/ dadurch solcher wind getrieben/',
    'das clavier und pedal ist unser hertz/',
    'in der kirchen gottes/',
    65.11627906976744,
    2]]},
 {'name': 'von anfang der welt biß hieher,', 'value': []},
 {'name': 'kürtzlich discurriret, zugleich auch die schöne herrliche vlmer orgel beschrieben wirdt.',
  'value': []},
 {'name': 'gehalten zu vlm im münster/',
  'value': [['E000073',
    'zu ulm in münster gethan.',
    'dergleichen sie anno 1531.',
    'auf daß sie aber die orgelwerck mögen verdächtig und verhast machen/',
    'gehalten zu vlm im münster/',
    57.692307692307686,
    5]]},
 {'name': 'an dessen kirchweyhtag/ den 1.', 'value': []},
 {'name': 'augusti dieses 1624. jahrs/', 'value': []},
 {'name': 'vnd auff begehren in offenen truck geben/', 'value': []},
 {'name': 'durch cunrad dieterich/ der heiligen schrifft doctorn/',
  'value': []},
 {'name': 'dero vlmischen kirchen superintendenten.', 'value': []},
 {'name': 'gedruckt zu vlm in der mederischen truckerey.', 'value': []},
 {'name': 'm. dc. xxiv', 'value': []},
 {'name': 'vakat', 'value': []},
 {'name': 'ehrnvöster/ vornehmer/ insonders geliebter herr vnd freundt/',
  'value': []},
 {'name': 'demnach ich ohnlangst bey vnserer nechstverwichnen kirchwey/',
  'value': []},
 {'name': 'ein christliche einfältige sermon/', 'value': []},
 {'name': 'von der jnstrumentalmusic vnd orgeln gehalten/', 'value': []},
 {'name': 'darinn ich von dem ersten brauch der musicalischen jnstrumenten/',
  'value': []},
 {'name': 'beym gottesdienst ins gemein/', 'value': []},
 {'name': 'besonders aber deren orgeln/', 'value': []},
 {'name': 'einen kurtz durchgehenden discurs gehalten/', 'value': []},
 {'name': 'vnd aber/ daß ich selbigen in offnen truck publiciren vnd außgehen lassen wolle/',
  'value': []},
 {'name': 'von etzlichen guthertzigen der kirchenmusicliebhabenden/',
  'value': []},
 {'name': 'von mir begehrt worden:', 'value': []},
 {'name': 'als hab ich denselbigen bevorderst/', 'value': []},
 {'name': 'dann auch andern ins gemein/', 'value': []},
 {'name': 'zu gutem willen hierin gern in rei memoriam gratificiren wöllen/',
  'value': []},
 {'name': 'vnangesehen mir nit bewust/', 'value': []},
 {'name': 'daß darinn was sonderbares/', 'value': []},
 {'name': 'so von andern/ der edlen musicalischen kunst wolbenambten rühmern/',
  'value': []},
 {'name': 'nicht besser tractiret vnd herauß gestrichen/', 'value': []},
 {'name': 'zu finden seyn werde.', 'value': []},
 {'name': 'solche aber hab ich dem herrn dero vrsachen zuschreiben wollen/',
  'value': []},
 {'name': 'weil nicht allein sein lieber alter vater/', 'value': []},
 {'name': 'herr adam steigleder/ mein sonders guter angenemer freund/',
  'value': []},
 {'name': 'nunmehr in das dreissigste jahr/', 'value': []},
 {'name': 'vnserer vlmischen weitberuffnen vnd berümbten orgel/', 'value': []},
 {'name': 'mit guten ehren vnd meniglichs löblichem ruhm vorgestanden.',
  'value': []},
 {'name': 'sondern er selbsten auch vor andern in der löblichen orgelkunst dermassen geübt vnd erfahren /',
  'value': [['E000078',
    'wie denn in denen vorigten jahren dergleichen orgelstürmerey hin und wieder an denen orten/',
    'ja gar die seeligkeit an solchen orgelsturm gelegen wäre/',
    'da diese falsche stieffbrüder eingeschlichen/',
    'sondern er selbsten auch vor andern in der löblichen orgelkunst dermassen geübt vnd erfahren /',
    52.97297297297297,
    39]]},
 {'name': 'daß er mit guten ehren für einen meister darinn passiren kan.',
  'value': []},
 {'name': 'gestalt dann seine/ so wol bey vns newlicher zeit/', 'value': []},
 {'name': 'mit nicht geringem belieben angehörte specimina,', 'value': []},
 {'name': 'als auch die bey sich habende allerhand schöne/',
  'value': [['E000073',
    'massen auch die blinden heyden aus dem liecht der natur solches selbst erkant haben/',
    'nemlich niemand anders als der allerweiseste gott/',
    'sonderlich plutarchus, dahero läst er sich ausdrücklich vernehmen:',
    'als auch die bey sich habende allerhand schöne/',
    53.43511450381679,
    43]]},
 {'name': 'liebliche/ kunstreiche compositiones, mehr dann gnug im werck selbsten bewehrten vnd außweisen;',
  'value': []},
 {'name': 'welche der edlen music vnd orgelkunst zu ehren/', 'value': []},
 {'name': 'ans tagliecht zugeben/ ich jhne hiemit veranlassen/', 'value': []},
 {'name': 'auch zugleich meine gute wolgeneigte affection,', 'value': []},
 {'name': 'gegen jhn vnd die seinen/', 'value': []},
 {'name': 'zuerkennen geben wollen/ mitt bitt/', 'value': []},
 {'name': 'er dieselbig zu freundtlichem willen auff vnd annemmen/',
  'value': []},
 {'name': 'vnnd meiner darbey im besten eingedenck sein/', 'value': []},
 {'name': 'auch den guten alten künstler/', 'value': []},
 {'name': 'herrn cunrad schotten/ welcher mit seinen blinden augen bey vnserer vlmischen orgel weyt mehr/',
  'value': []},
 {'name': 'als andere mit beeden augen sehende meister/', 'value': []},
 {'name': 'gesehen/ vnd selbiger zu jhrer verbesserung vnd perfection durch sein kunst vor der zeit auffgeholffen/',
  'value': []},
 {'name': 'mein freundtlichen gruß beneben allem gutem vermelden wolle:',
  'value': []},
 {'name': 'thue jhn hiemit gottlicher gnaden protection zu erwünschtem wolstand befehlen:',
  'value': []},
 {'name': 'geben inn vlm den 18.', 'value': []},
 {'name': 'augusti/ ablauffendens 1624. jahrs.', 'value': []},
 {'name': 'dessen freundwilliger chunrad dieterich d.', 'value': []},
 {'name': 'vers. 1.', 'value': []},
 {'name': 'lobet den herrn inn seinem heyligthumb/', 'value': []},
 {'name': 'lobet jhn in der feste seiner macht.', 'value': []},
 {'name': '2. lobet jhn inn seinen thaten/', 'value': []},
 {'name': 'lobet jhn in seiner grossen herligkeit.', 'value': []},
 {'name': '3. lobet jhn mit posaunen/', 'value': []},
 {'name': 'lobet jhn mit psalter vnd harpffen.', 'value': []},
 {'name': '4. lobet jhn mit paucken vnd reigen/', 'value': []},
 {'name': 'lobet jhn mit sayten vnnd pfeiffen.', 'value': []},
 {'name': '5. lobet jhn mit hellen cymbaln/', 'value': []},
 {'name': 'lobet jhn mit wolklingenden cymbaln.', 'value': []},
 {'name': '6. alles was odem hat/', 'value': []},
 {'name': 'lobe den herren/ alleluja.', 'value': []},
 {'name': 'es seind auff diesen gegenwertigen heutigen tag/', 'value': []},
 {'name': 'nuhnmehr 136. jahr/ daß dise vnsere schöne herrliche kirche/',
  'value': []},
 {'name': 'in jhrem baw/ wie sie da noch vor vnsern augen stehet/',
  'value': []},
 {'name': 'vollendet/ vnd demnach/ damahligem päbstischem gewohnlichem brauch gemäß/',
  'value': []},
 {'name': 'zu vnserer lieben frawen münster/', 'value': []},
 {'name': 'nit allein erstenmals offentlich consecriret vnd eingesegnet/',
  'value': []},
 {'name': 'sondern auch/ daß deren vergangnen kirchwey gedächtnuß/',
  'value': []},
 {'name': 'jährlich auff diesen tag widerholet würde/', 'value': []},
 {'name': 'angeordnet worden. wann dann nun/', 'value': []},
 {'name': 'beneben verrichtung vnsers christlichen gewonlichen gottesdiensts/',
  'value': []},
 {'name': 'wir auch zu christlicher begängnuß/', 'value': []},
 {'name': 'dieser vnserer järlichen kirchweyh/', 'value': []},
 {'name': 'jetzmahl in gottes namen bey einander versamblet/', 'value': []},
 {'name': 'dabey dann es dieses orths herkommens/', 'value': []},
 {'name': 'daß von christlichem kirchenwesen/', 'value': []},
 {'name': 'vnnd deren zugehörigen stucken/', 'value': []},
 {'name': 'inn denen kirchweyh predigten gehandelt wirdt:', 'value': []},
 {'name': 'als wil ebenmässiges mir auch dißmahls zu verrichten obligen.',
  'value': []},
 {'name': 'demnach ich aber hiebevor dergleichen vnderschiedene stuck/',
  'value': [['E000073',
    'gleichwie aber unser lieber gott nichts ohne mittel thut;',
    'dieweil sie die götter erfunden haben.',
    'also hat er auch hierinnen mittelbarer weise gehandelt/',
    'demnach ich aber hiebevor dergleichen vnderschiedene stuck/',
    48.275862068965516,
    92]]},
 {'name': 'so zum kirchenwesen nothwendig/', 'value': []},
 {'name': 'abgehandlet/ als nämblich/ 1.', 'value': []},
 {'name': 'von denen glocken /', 'value': []},
 {'name': 'damit zur kirchen geleütet wirdt.', 'value': []},
 {'name': '2. von dem offentlichen gemeinen choralvnnd figuralkirchengesang/',
  'value': []},
 {'name': 'so inn der kirchen vorgehen soll;', 'value': []},
 {'name': 'vnd aber zu der choralvnnd figuralmusic/', 'value': []},
 {'name': 'auch die jnstrumentalmusic gehörig:', 'value': []},
 {'name': 'so wil jch vor gegenwärtigen jargang dieselbige für mich nemmen/',
  'value': []},
 {'name': 'vnnd inn dieser kirchweyhpredigte allein etwas von der music/',
  'value': []},
 {'name': 'so in christlichen kirchen/', 'value': []},
 {'name': 'mit vnderschiedenen musicalischen jnstrumenten/', 'value': []},
 {'name': 'als posaunen/ flöten/ zincken/', 'value': []},
 {'name': 'pommern/ dolcianen/ vagotten/ schalmeyen/', 'value': []},
 {'name': 'geygen/ violen/ banduren/ harpffen/', 'value': []},
 {'name': 'zittern/ clauichordien/ positiuen/ andern dergleichen/',
  'value': []},
 {'name': 'sonderlich auch den orgeln/',
  'value': [['E000090',
    'lassen erklingen; auch uns also regieren/',
    'weil die welt stehet/',
    'daß/ wann diese orgel geschlagen wird/',
    'sonderlich auch den orgeln/',
    58.82352941176471,
    109],
   ['E000073',
    'sonderlich den orgeln/ gar nicht gut/',
    'massen auch viel calvinisten und zwinglianer der jnstrumentalmusic/',
    'darum die meisten fast dergleichen in ihren kirchen nicht gestatten/',
    'sonderlich auch den orgeln/',
    68.75,
    109]]},
 {'name': 'verrichtet wirdt/ handlen.', 'value': []},
 {'name': 'darzu vnns dann verlesne wort deß 150.', 'value': []},
 {'name': 'psalmens/ deß rechten musicalischen lobpsälmleins/', 'value': []},
 {'name': 'gute anleitung geben werden/', 'value': []},
 {'name': 'welche ich 1. schlecht vnd einfältig den worten nach erklären/',
  'value': []},
 {'name': 'vnd dann auch/ was wir darauß von jnstrumentalmusic vnnd orgeln/',
  'value': []},
 {'name': 'werden zubehalten haben/ mit wenigem andeuten wil.', 'value': []},
 {'name': 'weil denn nuhn david inn diesem vnserem vorhabenden psalmen alles was odem hat/',
  'value': []},
 {'name': 'den herrn zu loben vermanet/', 'value': []},
 {'name': 'vnd aber ewer lieben sampt vnd sonders mit einem menschlichen odem von gott begnadet:',
  'value': []},
 {'name': 'so wolle dieselbige vmb sovil desto fleissiger vnd andächtiger zu zuhören erbetten seyn.',
  'value': []},
 {'name': 'der grosse mächtige gott so vns allen odem geben/', 'value': []},
 {'name': 'vnd von vns allen darumb zu loben/',
  'value': [['E000078',
    'da fänget alles an zu leben.',
    'gewiß wo ein rechtschaffen orgelwerck in einer kirchen wird geschlagen/',
    'machet demnach eine wolbestalte orgel dem gottesdienst eine rechte zier und ansehen.',
    'vnd von vns allen darumb zu loben/',
    58.06451612903225,
    122]]},
 {'name': 'verleyhe hierzu sein gnad von oben herab/', 'value': []},
 {'name': 'durch christum jesum/ amen.', 'value': []},
 {'name': 'so vermahnet nun david inn seinem von vns vorgenommenen musicalischen lobpsälmlein/',
  'value': []},
 {'name': 'alle vnd jede menschen/', 'value': []},
 {'name': 'den herrn zuloben vnd zu preysen:', 'value': []},
 {'name': 'lobet den herrn/ sagt er.', 'value': []},
 {'name': 'da er dann durch den herrn verstehet gott den herrn/', 'value': []},
 {'name': 'welcher der einige herr vnd gott ist/',
  'value': [['E000108',
    'weil diese music eine gabe gotts ist/',
    'abusu. von dem gebrauch und mißbrauch der instrumentalmusic:',
    'als welcher flugs nach erschaffung der welt einen musicvater oder meister erwecket/',
    'welcher der einige herr vnd gott ist/',
    62.16216216216216,
    130]]},
 {'name': '5. buch mosi 6.4.', 'value': []},
 {'name': 'dann er der gott aller götter/', 'value': []},
 {'name': 'vnnd herr vber alle herren/', 'value': []},
 {'name': '5. buch mose 10.17.', 'value': []},
 {'name': 'ausser welchem sonsten keiner mehr/', 'value': []},
 {'name': '5. mos. cap. 4.35.', 'value': []},
 {'name': 'diesen herrn vnd gott wil nun david/', 'value': []},
 {'name': 'daß jhn alle menschen loben/',
  'value': [['E000073',
    'den jubal/ lamechs sohn/',
    'und zum ersten bey lebzeiten unsers ersten paradeisvaters adams/',
    'erwecket/ daß er zur music eine sonderbare inclination bekommen/',
    'daß jhn alle menschen loben/',
    53.84615384615385,
    138]]},
 {'name': 'theils vmb der feste seiner macht vnnd thaten/', 'value': []},
 {'name': 'theils vmb seiner grossen herrligkeit willen:', 'value': []},
 {'name': 'vmb der feste seiner macht/', 'value': []},
 {'name': 'weil seine macht vnendtlich/', 'value': []},
 {'name': 'vnd also vnvberwindtlich ist.', 'value': []},
 {'name': 'herr zebaoth/ wer ist wie du ein mächtiger gott?', 'value': []},
 {'name': 'psal. 89.9. dannenher er der gott der vnser stärcke ist/',
  'value': []},
 {'name': 'genennet/ psal. 81.2. welche feste seiner macht er sonderlich vnd fürnemblich in schöpffvnd erhaltung aller ding/',
  'value': []},
 {'name': 'in schützregiervnnd führung seiner kirchen/', 'value': []},
 {'name': 'vnnd aller seiner frommen churkinder/', 'value': []},
 {'name': 'mächtig erwisen/ vnd noch täglichen erweiset/', 'value': []},
 {'name': 'deßwegen er dann billich zu leben/', 'value': []},
 {'name': 'darumb sagt david: lobet jhn in der feste seiner macht/',
  'value': []},
 {'name': 'lobet jhn in seinen thaten.', 'value': []},
 {'name': 'vmb seiner grossen herrligkeit/', 'value': []},
 {'name': 'weil dieselbige vnermäßlich vnd vnergründtlich/', 'value': []},
 {'name': 'wegen seiner vnerforschlichen weißheit/', 'value': []},
 {'name': 'güte/ trew/ liebe/ gnad/', 'value': []},
 {'name': 'barmhertzigkeit/ gericht vnd warheit/', 'value': []},
 {'name': 'dardurch er dise seine herrligkeit erwisen vnd groß gemacht.',
  'value': []},
 {'name': 'o/ welche ein tieffe deß reichthumbs beyde der weißheit vnd erkäntnuß gottes?',
  'value': []},
 {'name': 'wie gar vnbegreifflich sind seine gerichte?', 'value': []},
 {'name': 'vnd vnerforschlich seine wege?', 'value': []},
 {'name': 'denn wer hat deß herrn sinn erkannt?', 'value': []},
 {'name': 'oder/ wer ist sein rathgeber gewesen?', 'value': []},
 {'name': 'darumben sagt davidt: lobet jhn in seiner grossen herrligkeit.',
  'value': []},
 {'name': 'diß loben soll aber nicht geschehen nuhr mit dem munde/',
  'value': []},
 {'name': 'mit gebett vnd dancksagung/', 'value': []},
 {'name': 'nicht nur mit der stimme/', 'value': []},
 {'name': 'mit modulierung geistlicher psalmen vnnd lobgesängen:',
  'value': []},
 {'name': 'sondern auch mit allerhand löblichen/', 'value': []},
 {'name': 'lieblichen musicalischen jnstrumenten: lobet jhn mit posaunen/',
  'value': []},
 {'name': 'lobet jhn mit psalter vnd harpffen/', 'value': []},
 {'name': 'lobet jhn mit paucken vnd reygen/', 'value': []},
 {'name': 'lobet jhn mit saiten vnd pfeiffen/', 'value': []},
 {'name': 'lobet jhn mit hellen cymbaln/', 'value': []},
 {'name': 'lobet jhn mit wolklingenden cymbalen.', 'value': []},
 {'name': 'siebnerley musicalische jnstrument erzehlet allhie david mit welchen man den herren loben soll:',
  'value': []},
 {'name': 'nämlich/ psalter/ harpffen/ posaunen/', 'value': []},
 {'name': 'paucken/ saiten/ pfeiffen/ cymbalen.', 'value': []},
 {'name': 'als welche damahls vnder dem volck gottes vor andern vblich vnd bräuchlich gewesen.',
  'value': []},
 {'name': 'wie aber solche jnstrumenta gestalt/', 'value': []},
 {'name': 'vnd was für ein beschaffenheit es mit jhnen gehabt/', 'value': []},
 {'name': 'kan man wegen mangel der antiquitäten/', 'value': []},
 {'name': 'eigentlich nicht wissen/ ohne was josephus der alten jüdischen geschichten schreiber hiervon meldet.',
  'value': []},
 {'name': 'derselbige schreibet aber im viertzehenden buch der jüdischen antiquitäten am 10.',
  'value': []},
 {'name': 'c. gedenckt deren auch sabellicus,', 'value': []},
 {'name': 'daß der psalter ein jnstrument gewesen/',
  'value': [['E000073',
    'psalter ist ein jnstrument gewesen/',
    'lobet ihn mit wohlklingenden cymbeln.',
    'welches man mit einem federkihl schlagen müssen/',
    'daß der psalter ein jnstrument gewesen/',
    83.78378378378379,
    186]]},
 {'name': 'so zehen sayten gehabt/',
  'value': [['E000073',
    'er habe 24. säiten gehabt/',
    'und schreibet hieronymus, ingleichen josephus,',
    'und sey formiret gewesen wie der griechische buchstab δ.',
    'so zehen sayten gehabt/',
    65.3061224489796,
    187]]},
 {'name': 'vnd mann mit einem plectro oder federkihl schlagen müssen/',
  'value': [['E000073',
    'welches man mit einem federkihl schlagen müssen/',
    'psalter ist ein jnstrument gewesen/',
    'der gleichen art etwa heutiges tages die cytharn seyn/',
    'vnd mann mit einem plectro oder federkihl schlagen müssen/',
    77.35849056603774,
    188]]},
 {'name': 'deßwegen es auch decachordum,', 'value': []},
 {'name': 'sonst cinnyra od auch cithara genant/', 'value': []},
 {'name': 'dergleichen art etwa die cytharn seyn/',
  'value': [['E000073',
    'der gleichen art etwa heutiges tages die cytharn seyn/',
    'welches man mit einem federkihl schlagen müssen/',
    'und schreibet hieronymus, ingleichen josephus,',
    'dergleichen art etwa die cytharn seyn/',
    82.6086956521739,
    191]]},
 {'name': 'so wir heutiges tags gebrauchen:', 'value': []},
 {'name': 'wiewol hieronymus schreibet/ daß bey den hebreern oder juden die cythar oder psalter vier vnd zweintzig saiten gehabt/',
  'value': []},
 {'name': 'vnnd wie der griechische buchstab δ formiert oder gebildet gewesen/',
  'value': [['E000073',
    'und sey formiret gewesen wie der griechische buchstab δ.',
    'er habe 24. säiten gehabt/',
    'die harpffe ist ein jnstrument gewesen von 12.',
    'vnnd wie der griechische buchstab δ formiert oder gebildet gewesen/',
    53.65853658536586,
    194]]},
 {'name': 'dergleichen auß josepho vnd hieronymo auch polidorus virgilius erwehnet.',
  'value': []},
 {'name': 'die harpffe ist ein jnstrument gewesen vonn zwölff saiten/',
  'value': [['E000073',
    'die harpffe ist ein jnstrument gewesen von 12.',
    'und sey formiret gewesen wie der griechische buchstab δ.',
    'säiten/ welches man mit den fingern greiffen müssen.',
    'die harpffe ist ein jnstrument gewesen vonn zwölff saiten/',
    82.6923076923077,
    196]]},
 {'name': 'welchs man mit den fingern greiffen müssen/',
  'value': [['E000073',
    'säiten/ welches man mit den fingern greiffen müssen.',
    'die harpffe ist ein jnstrument gewesen von 12.',
    'posaunen hat man mit dem munde geblasen/',
    'welchs man mit den fingern greiffen müssen/',
    88.42105263157895,
    197]]},
 {'name': 'wirdt sonst nablum oder nabla genandt/', 'value': []},
 {'name': 'dannenhero vnsere harpffen/ so wir noch heutigs tags gebrauchen jhren nahmen haben.',
  'value': []},
 {'name': 'posaunen hat man mit dem mund geblasen/',
  'value': [['E000073',
    'posaunen hat man mit dem munde geblasen/',
    'säiten/ welches man mit den fingern greiffen müssen.',
    'darunter zincken/ trommeten/ krumhörner und dergleichen mögen verstanden werden.',
    'posaunen hat man mit dem mund geblasen/',
    98.73417721518987,
    200]]},
 {'name': 'darunder dann zincken/ trommeten/', 'value': []},
 {'name': 'krummhorn/ andere beröhrte jnstrumenta mehr verstanden.',
  'value': []},
 {'name': 'paucken aber hat man mit besonderen schlegelen oder knüppelein geschlagen/',
  'value': []},
 {'name': 'dergleichen noch heutigs tags im brauch.',
  'value': [['E000073',
    'paucken sind noch heutiges tages im gebrauch.',

In [80]:
lines_cleaned = []
for line in lines_with_data:
    line_info = {}
    line_info["text"] = line["name"]
    line_info["quotes"] = len(line["value"])
    line_info["details"] = line["value"]
    lines_cleaned.append(line_info)

In [81]:
len(lines_cleaned)

1607

In [82]:
percent = len(lines_cleaned)/100

In [197]:
cleaned

{'E000001': {'title': 'Christliche Predigt (Tübingen 1602)',
  'year': '1602',
  'length': 6560,
  'worte_bibel': 380,
  'worte_quellen': 464,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Ps 150',
  'verlagsort': 'Tübingen',
  'einweihungsort': 'Memmingen'},
 'E000002': {'title': 'Musica instrumentalis (Meißen 1605)',
  'year': '1605',
  'length': 9118,
  'worte_bibel': 1825,
  'worte_quellen': 5,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Ps 69,3',
  'verlagsort': 'Leipzig',
  'einweihungsort': 'Meißen'},
 'E000003': {'title': 'Vlmische Orgel Predigt (Ulm 1624)',
  'year': '1624',
  'length': 10834,
  'worte_bibel': 498,
  'worte_quellen': 1464,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Ps 150, 1-6',
  'verlagsort': 'Ulm',
  'einweihungsort': 'Ulm, Münster ; E030003'},
 'E000007': {'title': 'Predigt bey der feyerlichen Einweihung der neuen Orgel (Magdeburg 1798)',
  'year': '1798',
  'length': 4611,
  'worte_bibel': 260,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 64,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Kol 3, 16',
  'verlagsort': 'Magdeburg',
  'einweihungsort': 'Magdeburg, St. Katharinen ; E030020'},
 'E000008': {'title': 'Predigt Bey der Einweihung einer Orgel (Leipzig 1797)',
  'year': '1797',
  'length': 3191,
  'worte_bibel': 32,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 84,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Ps 66, 1-3',
  'verlagsort': 'Leipzig',
  'einweihungsort': ''},
 'E000009': {'title': 'Predigt bey Einweyhung der Orgel (s.l. 1795)',
  'year': '1795',
  'length': 3719,
  'worte_bibel': 113,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Mt 7, 15-23',
  'verlagsort': 's.l.',
  'einweihungsort': 'Gröba, Kirche ; E030636'},
 'E000014': {'title': 'Gast-Predigt (Ulm 1781)',
  'year': '1781',
  'length': 3264,
  'worte_bibel': 436,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Ps 92, 1-5',
  'verlagsort': 'Ulm',
  'einweihungsort': 'Ulm, Barfüßerkirche ; E030003'},
 'E000015': {'title': 'Rede und Predigt bey Einweihung der neuen Orgel (Stockholm 1781)',
  'year': '1781',
  'length': 5754,
  'worte_bibel': 354,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 28,
  'zitierte_musikwerke': 6,
  'bibelstelle': 'Lk 1,57-80',
  'verlagsort': 'Stockholm',
  'einweihungsort': 'Stockholm, Gertrudskirche ; E030017'},
 'E000016': {'title': 'Der Dienst der Orgeln (Jena 1778)',
  'year': '1778',
  'length': 3798,
  'worte_bibel': 143,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': '1 Chr 16,8–10',
  'verlagsort': 'Jena',
  'einweihungsort': 'Tröbnitz'},
 'E000020': {'title': 'Predigt am Feste der Heimsuchung Mariae (Rostock 1770)',
  'year': '1770',
  'length': 6519,
  'worte_bibel': 179,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 77,
  'zitierte_musikwerke': 2,
  'bibelstelle': 'Lk 1, 39-45',
  'verlagsort': 'Rostock',
  'einweihungsort': 'Rostock, St. Marien ; E030039'},
 'E000021': {'title': 'Das heilige und fröliche Aufsehen (Tübingen 1767)',
  'year': '1767',
  'length': 12210,
  'worte_bibel': 666,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 137,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Lk 21,25–36',
  'verlagsort': 'Tübingen',
  'einweihungsort': 'Balingen'},
 'E000023': {'title': 'Der rechte Gebrauch der Orgeln (Altenburg 1766)',
  'year': '1766',
  'length': 7813,
  'worte_bibel': 592,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 4,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Eph 5,18–20',
  'verlagsort': 'Altenburg (Thüringen)',
  'einweihungsort': 'Gödern'},
 'E000024': {'title': 'Die heiligen Verrichtungen in dem Hause des Herrn (Eisenach 1765)',
  'year': '1765',
  'length': 7481,
  'worte_bibel': 345,
  'worte_quellen': 26,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 57,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Lk 19, 41-48',
  'verlagsort': 'Eisenach',
  'einweihungsort': 'Ilmenau, St. Jakobus ;  E030124'},
 'E000027': {'title': 'Der Christen gerechte Freude (Breslau 1761)',
  'year': '1761',
  'length': 10249,
  'worte_bibel': 309,
  'worte_quellen': 1135,
  'worte_orgelpredigt': 1,
  'worte_musikwerk': 230,
  'zitierte_musikwerke': 6,
  'bibelstelle': 'Mt 18, 1-11',
  'verlagsort': 'Breslau',
  'einweihungsort': 'Breslau, Elisabethkirche ; E030113'},
 'E000029': {'title': 'Christliche Predigt (Tübingen 1606)',
  'year': '1606',
  'length': 8112,
  'worte_bibel': 814,
  'worte_quellen': 381,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 26,
  'zitierte_musikwerke': 5,
  'bibelstelle': 'Eph 5,19',
  'verlagsort': 'Tübingen',
  'einweihungsort': 'Kaufbeuren'},
 'E000030': {'title': 'Elogium Organi Musici (Altenburg 1610)',
  'year': '1610',
  'length': 6360,
  'worte_bibel': 1005,
  'worte_quellen': 705,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 23,
  'zitierte_musikwerke': 1,
  'bibelstelle': '2 Chr 29,25–36',
  'verlagsort': 'Altenburg (Thüringen)',
  'einweihungsort': 'Meuselwitz'},
 'E000034': {'title': 'Lob= und Danck=Predigt (Berlin 1753)',
  'year': '1753',
  'length': 3052,
  'worte_bibel': 273,
  'worte_quellen': 60,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 7,
  'zitierte_musikwerke': 1,
  'bibelstelle': '1 Chr 17, 8-10',
  'verlagsort': 'Berlin',
  'einweihungsort': 'Berlin, Neue Kirche ; E030049'},
 'E000035': {'title': 'Musicalische Orgel= Lob= und Ehren=Predigt (s.l. 1751)',
  'year': '1751',
  'length': 3948,
  'worte_bibel': 283,
  'worte_quellen': 0,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Hld 2,14',
  'verlagsort': 's.l.',
  'einweihungsort': 'Kaysersberg, Benediktinerkloster Alspach ; E030705'},
 'E000036': {'title': 'Die heilige Sabbaths-Lust an dem Herrn (Danzig 1749)',
  'year': '1749',
  'length': 13867,
  'worte_bibel': 1348,
  'worte_quellen': 1518,
  'worte_orgelpredigt': 45,
  'worte_musikwerk': 796,
  'zitierte_musikwerke': 25,
  'bibelstelle': 'Lk 14, 1-2',
  'verlagsort': 'Danzig',
  'einweihungsort': 'Elbing, Heilig-Geist-Kirche ; E030100'},
 'E000037': {'title': 'Christliche Predigt (Straßburg 1749)',
  'year': '1749',
  'length': 3410,
  'worte_bibel': 371,
  'worte_quellen': 8,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 22,
  'zitierte_musikwerke': 2,
  'bibelstelle': 'Ps 150',
  'verlagsort': 'Straßburg',
  'einweihungsort': 'Straßburg, Temple Neuf ; E030098'},
 'E000038': {'title': 'Den rechtmäßigen Gebrauch der Music (Königsberg 1747)',
  'year': '1747',
  'length': 10643,
  'worte_bibel': 595,
  'worte_quellen': 128,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 473,
  'zitierte_musikwerke': 9,
  'bibelstelle': 'Ps 150, 1-6',
  'verlagsort': 'Königsberg (Preußen)',
  'einweihungsort': 'Königsberg (Preußen), Altroßgärter Kirche ; E030078'},
 'E000039': {'title': 'Winnedisches Reminiscere (Stuttgart 1740)',
  'year': '1740',
  'length': 8043,
  'worte_bibel': 672,
  'worte_quellen': 4,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 174,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Ps 150, 1-6',
  'verlagsort': 'Stuttgart',
  'einweihungsort': 'Winnenden, St. Jakobus ;  E030142'},
 'E000041': {'title': 'Die Billige Orgel-Freude (Danzig 1739)',
  'year': '1739',
  'length': 7427,
  'worte_bibel': 1207,
  'worte_quellen': 143,
  'worte_orgelpredigt': 7,
  'worte_musikwerk': 128,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Lk 10,23–27',
  'verlagsort': 'Danzig',
  'einweihungsort': 'Danzig, Salvatorkirche ; E030070'},
 'E000042': {'title': 'Das Neue Lied (Freiberg 1735)',
  'year': '1735',
  'length': 14868,
  'worte_bibel': 860,
  'worte_quellen': 438,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 190,
  'zitierte_musikwerke': 17,
  'bibelstelle': 'Offb 14, 1-5',
  'verlagsort': 'Freiberg',
  'einweihungsort': 'Freiberg, Petrikirche ; E030091'},
 'E000045': {'title': 'Hymnosophia sacra (Billwerder 1728)',
  'year': '1728',
  'length': 15581,
  'worte_bibel': 1113,
  'worte_quellen': 1666,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 93,
  'zitierte_musikwerke': 8,
  'bibelstelle': 'Mt 18',
  'verlagsort': 'Billwerder',
  'einweihungsort': 'Billwerder, St. Nikolai ; E030203'},
 'E000046': {'title': 'Die edle und wohlgeordnete Music der Gläubigen (Halle 1727)',
  'year': '1727',
  'length': 15256,
  'worte_bibel': 1440,
  'worte_quellen': 1569,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 191,
  'zitierte_musikwerke': 6,
  'bibelstelle': 'Eph 5, 19',
  'verlagsort': 'Halle (Saale)',
  'einweihungsort': 'Berlin-Mitte, Marienkirche ; E030049'},
 'E000048': {'title': 'Die verstimmte Zwölff Grösseste Pfeiffen (Tübingen s.a.)',
  'year': '1726',
  'length': 7507,
  'worte_bibel': 709,
  'worte_quellen': 19,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 107,
  'zitierte_musikwerke': 5,
  'bibelstelle': 'Lk 22, 24-30',
  'verlagsort': 'Tübingen',
  'einweihungsort': 'Calw, Stadtkirche ; E030158'},
 'E000051': {'title': 'Die Kneiphöffsche laute Orgel=Stimme (Königsberg 1721)',
  'year': '1721',
  'length': 7536,
  'worte_bibel': 1252,
  'worte_quellen': 73,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Lk 17, 15',
  'verlagsort': 'Königsberg (Preußen)',
  'einweihungsort': 'Königsberg (Preußen), Dom ; E030078'},
 'E000052': {'title': 'Ein wolgerührtes Orgel=Werck (Königsberg 1721)',
  'year': '1721',
  'length': 9326,
  'worte_bibel': 1100,
  'worte_quellen': 141,
  'worte_orgelpredigt': 37,
  'worte_musikwerk': 331,
  'zitierte_musikwerke': 11,
  'bibelstelle': 'Gal 5, 16',
  'verlagsort': 'Königsberg (Preußen)',
  'einweihungsort': 'Königsberg (Preußen), Dom ; E030078'},
 'E000053': {'title': 'Vivum Dei Organum (Schneeberg s.a.)',
  'year': '1720',
  'length': 21940,
  'worte_bibel': 1827,
  'worte_quellen': 4788,
  'worte_orgelpredigt': 630,
  'worte_musikwerk': 173,
  'zitierte_musikwerke': 5,
  'bibelstelle': '2 Kor 4, 13',
  'verlagsort': 'Schneeberg (Erzgebirge)',
  'einweihungsort': 'Neustädtel, Zu unserer lieben Frauen ; E030077'},
 'E000055': {'title': 'Davids Vermahnung (Dresden 1711)',
  'year': '1711',
  'length': 14872,
  'worte_bibel': 1819,
  'worte_quellen': 495,
  'worte_orgelpredigt': 10,
  'worte_musikwerk': 153,
  'zitierte_musikwerke': 15,
  'bibelstelle': 'Ps 150',
  'verlagsort': 'Dresden',
  'einweihungsort': 'Hohenwussen (Naundorf), Dorfkirche ; E030074'},
 'E000056': {'title': 'Orgel Weih-Predigt (Ansbach 1709)',
  'year': '1709',
  'length': 6116,
  'worte_bibel': 684,
  'worte_quellen': 495,
  'worte_orgelpredigt': 210,
  'worte_musikwerk': 5,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Eph 5, 18-19',
  'verlagsort': 'Ansbach',
  'einweihungsort': 'Crailsheim, Johanneskirche ; E030233'},
 'E000057': {'title': 'Das rein-gestimmte Orgel-Werk unsers Herzens (Nürnberg s.a.)',
  'year': '1709',
  'length': 10818,
  'worte_bibel': 1428,
  'worte_quellen': 713,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 221,
  'zitierte_musikwerke': 5,
  'bibelstelle': 'Mt 18, 23-35',
  'verlagsort': 'Nürnberg',
  'einweihungsort': 'Nürnberg, Predigerkirche ; E030146'},
 'E000058': {'title': 'Christliche Orgel-Predigt (Danzig s.a.)',
  'year': '1704',
  'length': 5694,
  'worte_bibel': 372,
  'worte_quellen': 504,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 170,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Mt 9, 23-25',
  'verlagsort': 'Danzig',
  'einweihungsort': 'Danzig, Trinitatis-Kirche ; E030070'},
 'E000059': {'title': 'Einweihungs-Predigt (Görlitz 1704)',
  'year': '1704',
  'length': 10645,
  'worte_bibel': 969,
  'worte_quellen': 1672,
  'worte_orgelpredigt': 3,
  'worte_musikwerk': 119,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Lk 18, 9-14',
  'verlagsort': 'no_name',
  'einweihungsort': 'Görlitz, St. Peter und Paul ;  E030069'},
 'E000060': {'title': 'Die Christliche Harmonie (Jena 1700)',
  'year': '1700',
  'length': 5245,
  'worte_bibel': 181,
  'worte_quellen': 151,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 178,
  'zitierte_musikwerke': 10,
  'bibelstelle': 'Mt 5,20–26',
  'verlagsort': 'Jena',
  'einweihungsort': 'Leubingen, St. Petri ; E030268'},
 'E000061': {'title': 'Einweihungs-Predigt (Berlin 1730)',
  'year': '1730',
  'length': 12334,
  'worte_bibel': 2624,
  'worte_quellen': 838,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 611,
  'zitierte_musikwerke': 6,
  'bibelstelle': 'Mt 21, 9',
  'verlagsort': 'Berlin',
  'einweihungsort': 'Wriezen, St. Marien ; E030148'},
 'E000063': {'title': 'Schuldiges Lob Gottes (Nürnberg 1696)',
  'year': '1696',
  'length': 6055,
  'worte_bibel': 369,
  'worte_quellen': 452,
  'worte_orgelpredigt': 130,
  'worte_musikwerk': 0,
  'zitierte_musikwerke': 0,
  'bibelstelle': 'Ps 150,4',
  'verlagsort': 'Nürnberg',
  'einweihungsort': 'Nürnberg'},
 'E000065': {'title': 'Eine Christliche Orgel=Predigt (Danzig 1695)',
  'year': '1695',
  'length': 10924,
  'worte_bibel': 1499,
  'worte_quellen': 956,
  'worte_orgelpredigt': 1,
  'worte_musikwerk': 76,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Mt 22,1–15',
  'verlagsort': 'Danzig',
  'einweihungsort': 'Petersdorf'},
 'E000067': {'title': 'Organo-Praxis Mystica (Görlitz 1689)',
  'year': '1689',
  'length': 13070,
  'worte_bibel': 1478,
  'worte_quellen': 525,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 7,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Mkᵜ7,31–37',
  'verlagsort': 'Görlitz',
  'einweihungsort': 'Görlitz'},
 'E000068': {'title': 'Das dem Allmächtigen abzustattende Lob (Altenburg s.a.)',
  'year': '1687',
  'length': 11791,
  'worte_bibel': 413,
  'worte_quellen': 841,
  'worte_orgelpredigt': 184,
  'worte_musikwerk': 18,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Psᵜ150,4–6',
  'verlagsort': 'Altenburg (Thüringen)',
  'einweihungsort': 'Altenburg (Thüringen)'},
 'E000069': {'title': 'Organum Mysticum (Dresden 1686)',
  'year': '1686',
  'length': 21973,
  'worte_bibel': 2389,
  'worte_quellen': 1168,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 251,
  'zitierte_musikwerke': 7,
  'bibelstelle': 'Mt 6,31–33',
  'verlagsort': 'Dresden',
  'einweihungsort': 'Lindenau (Oberlausitz)'},
 'E000070': {'title': 'Cithara Theologica (Schleusingen 1683)',
  'year': '1683',
  'length': 10076,
  'worte_bibel': 1228,
  'worte_quellen': 376,
  'worte_orgelpredigt': 409,
  'worte_musikwerk': 420,
  'zitierte_musikwerke': 16,
  'bibelstelle': 'Lk 24, 46-47',
  'verlagsort': 'Schleusingen',
  'einweihungsort': 'Veilsdorf'},
 'E000072': {'title': 'Gott und Gnug (Meißen 1681)',
  'year': '1681',
  'length': 14607,
  'worte_bibel': 1992,
  'worte_quellen': 794,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 607,
  'zitierte_musikwerke': 18,
  'bibelstelle': 'Ps 150,6',
  'verlagsort': 'Meißen',
  'einweihungsort': 'Frauenhain, Dorfkirche ; E030257'},
 'E000073': {'title': 'Geistlich= und Gott wohlgefälliges Lob- und Danck-Opffer (Bayreuth 1680)',
  'year': '1680',
  'length': 8227,
  'worte_bibel': 1003,
  'worte_quellen': 454,
  'worte_orgelpredigt': 1283,
  'worte_musikwerk': 206,
  'zitierte_musikwerke': 7,
  'bibelstelle': 'Ps 150',
  'verlagsort': 'Bayreuth',
  'einweihungsort': 'Bindlach, Evangelische Pfarrkirche ; E030263'},
 'E000074': {'title': 'Glaubiger Kinder Gottes Gott=gefällige Music (Augsburg 1721)',
  'year': '1721',
  'length': 2107,
  'worte_bibel': 55,
  'worte_quellen': 24,
  'worte_orgelpredigt': 57,
  'worte_musikwerk': 1,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Eph 5,15ff.',
  'verlagsort': 'Augsburg',
  'einweihungsort': 'Augsburg, St. Ulrich ; E030314'},
 'E000075': {'title': 'Das Lieblich=klingende Orgeln und Saiten=Spiel (Coburg 1676)',
  'year': '1676',
  'length': 4884,
  'worte_bibel': 755,
  'worte_quellen': 606,
  'worte_orgelpredigt': 18,
  'worte_musikwerk': 211,
  'zitierte_musikwerke': 13,
  'bibelstelle': 'Mt 9,1–8',
  'verlagsort': 'Coburg',
  'einweihungsort': 'Mupperg'},
 'E000078': {'title': 'Das fröliche Halleluja (Wittenberg 1675)',
  'year': '1675',
  'length': 9487,
  'worte_bibel': 553,
  'worte_quellen': 466,
  'worte_orgelpredigt': 1206,
  'worte_musikwerk': 151,
  'zitierte_musikwerke': 5,
  'bibelstelle': 'Ps 150',
  'verlagsort': 'Wittenberg',
  'einweihungsort': 'Luckau'},
 'E000079': {'title': 'Denck- und Danck-Säule (Rothenburg ob der Tauber [1673])',
  'year': '1673',
  'length': 9022,
  'worte_bibel': 637,
  'worte_quellen': 2802,
  'worte_orgelpredigt': 686,
  'worte_musikwerk': 147,
  'zitierte_musikwerke': 4,
  'bibelstelle': '',
  'verlagsort': 'Rothenburg ob der Tauber',
  'einweihungsort': 'Rothenburg ob der Tauber'},
 'E000082': {'title': 'Geistliches Orgelwerk (Erfurt 1672)',
  'year': '1672',
  'length': 8023,
  'worte_bibel': 1447,
  'worte_quellen': 1332,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 201,
  'zitierte_musikwerke': 12,
  'bibelstelle': 'Lk 8,4–15',
  'verlagsort': 'Erfurt',
  'einweihungsort': 'Nottleben'},
 'E000083': {'title': 'Das Gott=Lob=Schallende Hosianna (Leipzig 1671)',
  'year': '1671',
  'length': 6911,
  'worte_bibel': 687,
  'worte_quellen': 248,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 86,
  'zitierte_musikwerke': 4,
  'bibelstelle': 'Mt 21,9',
  'verlagsort': 'Leipzig',
  'einweihungsort': 'Pomßen'},
 'E000085': {'title': 'Das fröliche Hallelujah (Halle 1667)',
  'year': '1667',
  'length': 6785,
  'worte_bibel': 635,
  'worte_quellen': 162,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 103,
  'zitierte_musikwerke': 8,
  'bibelstelle': 'Ps 150, 1-6',
  'verlagsort': 'Halle (Saale)',
  'einweihungsort': 'Halle (Saale)'},
 'E000086': {'title': 'Orgel=Predigt (Arnstadt 1666)',
  'year': '1666',
  'length': 8643,
  'worte_bibel': 1899,
  'worte_quellen': 550,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 70,
  'zitierte_musikwerke': 3,
  'bibelstelle': 'Ps 150, 1-6',
  'verlagsort': 'Arnstadt',
  'einweihungsort': 'Holzhausen'},
 'E000089': {'title': 'Encoenia HierOrganica (Halle 1664)',
  'year': '1664',
  'length': 4316,
  'worte_bibel': 429,
  'worte_quellen': 104,
  'worte_orgelpredigt': 0,
  'worte_musikwerk': 42,
  'zitierte_musikwerke': 4,
  'bibelstelle': 'Ps 150, 4',
  'verlagsort': 'Halle (Saale)',
  'einweihungsort': 'Halle (Saale), Unser Lieben Frauen ; E030018'},
 'E000090': {'title': 'Organolustria Evangelico-Stambachiana (Hof 1660)',
  'year': '1660',
  'length': 6905,
  'worte_bibel': 545,
  'worte_quellen': 161,
  'worte_orgelpredigt': 351,
  'worte_musikwerk': 21,
  'zitierte_musikwerke': 1,
  'bibelstelle': 'Mk 7, 31-37',
  'verlagsort': 'Hof (Saale)',
  'einweihungsort': 'Stammbach, Marienkirche ; E030182'},
 'E000091': {'title': 'Stolpenische Ehren-Crone (Dresden 1652)',
  'year': '1652',
  'length': 6155,
  'worte_bibel': 553,
  'worte_quellen': 871,
  'worte_orgelpredigt': 294,
  'worte_musikwerk': 147,
  'zitierte_musikwerke': 5,
  'bibelstelle': '1 Tim 4, 4-5',
  'verlagsort': 'Dresden',
  'einweihungsort': 'Stolpen, Stadtkirche ; E030306'},
 'E000092': {'title': 'Organologismos (Dresden 1651)',
  'year': '1651',
  'length': 17448,
  'worte_bibel': 2389,
  'worte_quellen': 1851,
  'worte_orgelpredigt': 141,
  'worte_musikwerk': 159,
  'zitierte_musikwerke': 7,
  'bibelstelle': 'Lk 15,1–11',
  'verlagsort': 'Dresden',
  'einweihungsort': 'Leubnitz'},
 'E000095': {'title': 'Längst=gewüntzschte Mittweidische Orgel=Freude (Dresden 1648)',
  'year': '1648',
  'length': 10030,
  'worte_bibel': 993,
  'worte_quellen': 175,
  'worte_orgelpredigt': 648,
  'worte_musikwerk': 60,
  'zitierte_musikwerke': 8,
  'bibelstelle': 'Sir 40,19–20',
  'verlagsort': 'Dresden',
  'einweihungsort': 'Mittweida'},
 'E000096': {'title': 'Kostbare Bosische Orgel (Zwickau 1647)',
  'year': '1647',
  'length': 10247,
  'worte_bibel': 1103,

In [84]:
quote_distr = []
for i in range(len(lines_cleaned)):
    quote_distr.append([i, lines_cleaned[i]["quotes"]])

In [85]:
quote_distr

[[0, 0],
 [1, 0],
 [2, 1],
 [3, 0],
 [4, 0],
 [5, 1],
 [6, 0],
 [7, 0],
 [8, 0],
 [9, 0],
 [10, 0],
 [11, 0],
 [12, 0],
 [13, 0],
 [14, 0],
 [15, 0],
 [16, 0],
 [17, 0],
 [18, 0],
 [19, 0],
 [20, 0],
 [21, 0],
 [22, 0],
 [23, 0],
 [24, 0],
 [25, 0],
 [26, 0],
 [27, 0],
 [28, 0],
 [29, 0],
 [30, 0],
 [31, 0],
 [32, 0],
 [33, 0],
 [34, 0],
 [35, 0],
 [36, 0],
 [37, 0],
 [38, 0],
 [39, 1],
 [40, 0],
 [41, 0],
 [42, 0],
 [43, 1],
 [44, 0],
 [45, 0],
 [46, 0],
 [47, 0],
 [48, 0],
 [49, 0],
 [50, 0],
 [51, 0],
 [52, 0],
 [53, 0],
 [54, 0],
 [55, 0],
 [56, 0],
 [57, 0],
 [58, 0],
 [59, 0],
 [60, 0],
 [61, 0],
 [62, 0],
 [63, 0],
 [64, 0],
 [65, 0],
 [66, 0],
 [67, 0],
 [68, 0],
 [69, 0],
 [70, 0],
 [71, 0],
 [72, 0],
 [73, 0],
 [74, 0],
 [75, 0],
 [76, 0],
 [77, 0],
 [78, 0],
 [79, 0],
 [80, 0],
 [81, 0],
 [82, 0],
 [83, 0],
 [84, 0],
 [85, 0],
 [86, 0],
 [87, 0],
 [88, 0],
 [89, 0],
 [90, 0],
 [91, 0],
 [92, 1],
 [93, 0],
 [94, 0],
 [95, 0],
 [96, 0],
 [97, 0],
 [98, 0],
 [99, 0],
 [100, 0],
 [101, 0],
 [102, 0],
 [103, 0],
 [104, 0],
 [105, 0],
 [106, 0],
 [107, 0],
 [108, 0],
 [109, 2],
 [110, 0],
 [111, 0],
 [112, 0],
 [113, 0],
 [114, 0],
 [115, 0],
 [116, 0],
 [117, 0],
 [118, 0],
 [119, 0],
 [120, 0],
 [121, 0],
 [122, 1],
 [123, 0],
 [124, 0],
 [125, 0],
 [126, 0],
 [127, 0],
 [128, 0],
 [129, 0],
 [130, 1],
 [131, 0],
 [132, 0],
 [133, 0],
 [134, 0],
 [135, 0],
 [136, 0],
 [137, 0],
 [138, 1],
 [139, 0],
 [140, 0],
 [141, 0],
 [142, 0],
 [143, 0],
 [144, 0],
 [145, 0],
 [146, 0],
 [147, 0],
 [148, 0],
 [149, 0],
 [150, 0],
 [151, 0],
 [152, 0],
 [153, 0],
 [154, 0],
 [155, 0],
 [156, 0],
 [157, 0],
 [158, 0],
 [159, 0],
 [160, 0],
 [161, 0],
 [162, 0],
 [163, 0],
 [164, 0],
 [165, 0],
 [166, 0],
 [167, 0],
 [168, 0],
 [169, 0],
 [170, 0],
 [171, 0],
 [172, 0],
 [173, 0],
 [174, 0],
 [175, 0],
 [176, 0],
 [177, 0],
 [178, 0],
 [179, 0],
 [180, 0],
 [181, 0],
 [182, 0],
 [183, 0],
 [184, 0],
 [185, 0],
 [186, 1],
 [187, 1],
 [188, 1],
 [189, 0],
 [190, 0],
 [191, 1],
 [192, 0],
 [193, 0],
 [194, 1],
 [195, 0],
 [196, 1],
 [197, 1],
 [198, 0],
 [199, 0],
 [200, 1],
 [201, 0],
 [202, 0],
 [203, 0],
 [204, 1],
 [205, 0],
 [206, 2],
 [207, 0],
 [208, 2],
 [209, 1],
 [210, 1],
 [211, 0],
 [212, 0],
 [213, 0],
 [214, 0],
 [215, 0],
 [216, 1],
 [217, 0],
 [218, 0],
 [219, 1],
 [220, 1],
 [221, 1],
 [222, 0],
 [223, 0],
 [224, 0],
 [225, 0],
 [226, 0],
 [227, 0],
 [228, 0],
 [229, 0],
 [230, 1],
 [231, 1],
 [232, 0],
 [233, 0],
 [234, 1],
 [235, 0],
 [236, 0],
 [237, 0],
 [238, 0],
 [239, 0],
 [240, 0],
 [241, 0],
 [242, 0],
 [243, 0],
 [244, 0],
 [245, 0],
 [246, 0],
 [247, 0],
 [248, 0],
 [249, 0],
 [250, 0],
 [251, 0],
 [252, 0],
 [253, 0],
 [254, 0],
 [255, 0],
 [256, 0],
 [257, 0],
 [258, 0],
 [259, 0],
 [260, 0],
 [261, 0],
 [262, 1],
 [263, 0],
 [264, 0],
 [265, 0],
 [266, 0],
 [267, 0],
 [268, 0],
 [269, 0],
 [270, 0],
 [271, 0],
 [272, 0],
 [273, 0],
 [274, 0],
 [275, 0],
 [276, 1],
 [277, 0],
 [278, 1],
 [279, 0],
 [280, 0],
 [281, 0],
 [282, 0],
 [283, 0],
 [284, 1],
 [285, 1],
 [286, 0],
 [287, 1],
 [288, 1],
 [289, 2],
 [290, 1],
 [291, 1],
 [292, 1],
 [293, 1],
 [294, 0],
 [295, 0],
 [296, 0],
 [297, 0],
 [298, 2],
 [299, 2],
 [300, 1],
 [301, 1],
 [302, 0],
 [303, 0],
 [304, 1],
 [305, 0],
 [306, 1],
 [307, 1],
 [308, 0],
 [309, 0],
 [310, 0],
 [311, 0],
 [312, 0],
 [313, 0],
 [314, 0],
 [315, 1],
 [316, 0],
 [317, 1],
 [318, 1],
 [319, 1],
 [320, 0],
 [321, 1],
 [322, 2],
 [323, 0],
 [324, 0],
 [325, 2],
 [326, 1],
 [327, 1],
 [328, 2],
 [329, 1],
 [330, 1],
 [331, 0],
 [332, 0],
 [333, 2],
 [334, 0],
 [335, 0],
 [336, 0],
 [337, 0],
 [338, 0],
 [339, 0],
 [340, 0],
 [341, 0],
 [342, 0],
 [343, 0],
 [344, 0],
 [345, 0],
 [346, 0],
 [347, 1],
 [348, 0],
 [349, 0],
 [350, 1],
 [351, 0],
 [352, 0],
 [353, 0],
 [354, 1],
 [355, 0],
 [356, 0],
 [357, 0],
 [358, 0],
 [359, 0],
 [360, 0],
 [361, 0],
 [362, 0],
 [363, 0],
 [364, 0],
 [365, 0],
 [366, 0],
 [367, 0],
 [368, 0],
 [369, 1],
 [370, 0],
 [371, 1],
 [372, 2],
 [373, 1],
 [374, 0],
 [375, 1],
 [376, 0],
 [377, 0],
 [378, 2],
 [379, 1],
 [380, 0],
 [381, 0],
 [382, 0],
 [383, 0],
 [384, 0],
 [385, 0],
 [386, 0],
 [387, 0],
 [388, 0],
 [389, 0],
 [390, 1],
 [391, 1],
 [392, 1],
 [393, 1],
 [394, 1],
 [395, 1],
 [396, 0],
 [397, 0],
 [398, 0],
 [399, 1],
 [400, 1],
 [401, 0],
 [402, 0],
 [403, 1],
 [404, 1],
 [405, 0],
 [406, 0],
 [407, 0],
 [408, 0],
 [409, 0],
 [410, 0],
 [411, 1],
 [412, 0],
 [413, 0],
 [414, 0],
 [415, 0],
 [416, 1],
 [417, 0],
 [418, 0],
 [419, 0],
 [420, 0],
 [421, 0],
 [422, 0],
 [423, 0],
 [424, 0],
 [425, 0],
 [426, 0],
 [427, 0],
 [428, 0],
 [429, 0],
 [430, 0],
 [431, 0],
 [432, 0],
 [433, 0],
 [434, 0],
 [435, 0],
 [436, 0],
 [437, 1],
 [438, 0],
 [439, 0],
 [440, 0],
 [441, 0],
 [442, 1],
 [443, 0],
 [444, 0],
 [445, 0],
 [446, 0],
 [447, 0],
 [448, 0],
 [449, 0],
 [450, 0],
 [451, 0],
 [452, 0],
 [453, 0],
 [454, 0],
 [455, 0],
 [456, 0],
 [457, 0],
 [458, 0],
 [459, 0],
 [460, 0],
 [461, 0],
 [462, 0],
 [463, 0],
 [464, 0],
 [465, 0],
 [466, 1],
 [467, 0],
 [468, 0],
 [469, 0],
 [470, 0],
 [471, 0],
 [472, 0],
 [473, 0],
 [474, 0],
 [475, 0],
 [476, 0],
 [477, 0],
 [478, 0],
 [479, 0],
 [480, 0],
 [481, 0],
 [482, 0],
 [483, 0],
 [484, 0],
 [485, 0],
 [486, 0],
 [487, 0],
 [488, 0],
 [489, 0],
 [490, 0],
 [491, 0],
 [492, 0],
 [493, 0],
 [494, 0],
 [495, 0],
 [496, 0],
 [497, 0],
 [498, 0],
 [499, 0],
 [500, 0],
 [501, 0],
 [502, 0],
 [503, 0],
 [504, 0],
 [505, 0],
 [506, 0],
 [507, 0],
 [508, 0],
 [509, 0],
 [510, 0],
 [511, 0],
 [512, 0],
 [513, 0],
 [514, 0],
 [515, 0],
 [516, 0],
 [517, 0],
 [518, 0],
 [519, 0],
 [520, 0],
 [521, 0],
 [522, 0],
 [523, 0],
 [524, 0],
 [525, 0],
 [526, 0],
 [527, 0],
 [528, 0],
 [529, 0],
 [530, 0],
 [531, 0],
 [532, 0],
 [533, 0],
 [534, 0],
 [535, 0],
 [536, 0],
 [537, 0],
 [538, 0],
 [539, 0],
 [540, 0],
 [541, 0],
 [542, 0],
 [543, 0],
 [544, 0],
 [545, 0],
 [546, 0],
 [547, 0],
 [548, 0],
 [549, 0],
 [550, 1],
 [551, 0],
 [552, 0],
 [553, 0],
 [554, 0],
 [555, 0],
 [556, 0],
 [557, 0],
 [558, 0],
 [559, 1],
 [560, 0],
 [561, 0],
 [562, 0],
 [563, 0],
 [564, 0],
 [565, 0],
 [566, 0],
 [567, 0],
 [568, 0],
 [569, 0],
 [570, 0],
 [571, 0],
 [572, 1],
 [573, 0],
 [574, 0],
 [575, 0],
 [576, 1],
 [577, 0],
 [578, 0],
 [579, 1],
 [580, 0],
 [581, 0],
 [582, 0],
 [583, 0],
 [584, 1],
 [585, 2],
 [586, 1],
 [587, 0],
 [588, 0],
 [589, 1],
 [590, 0],
 [591, 0],
 [592, 0],
 [593, 0],
 [594, 0],
 [595, 0],
 [596, 0],
 [597, 0],
 [598, 0],
 [599, 0],
 [600, 2],
 [601, 0],
 [602, 0],
 [603, 0],
 [604, 0],
 [605, 0],
 [606, 0],
 [607, 0],
 [608, 1],
 [609, 0],
 [610, 0],
 [611, 0],
 [612, 0],
 [613, 0],
 [614, 0],
 [615, 0],
 [616, 1],
 [617, 1],
 [618, 1],
 [619, 1],
 [620, 0],
 [621, 0],
 [622, 1],
 [623, 0],
 [624, 0],
 [625, 0],
 [626, 0],
 [627, 0],
 [628, 0],
 [629, 1],
 [630, 0],
 [631, 0],
 [632, 0],
 [633, 0],
 [634, 0],
 [635, 0],
 [636, 0],
 [637, 0],
 [638, 0],
 [639, 0],
 [640, 0],
 [641, 0],
 [642, 0],
 [643, 0],
 [644, 0],
 [645, 0],
 [646, 0],
 [647, 0],
 [648, 0],
 [649, 0],
 [650, 0],
 [651, 0],
 [652, 1],
 [653, 0],
 [654, 0],
 [655, 1],
 [656, 1],
 [657, 0],
 [658, 1],
 [659, 0],
 [660, 1],
 [661, 0],
 [662, 0],
 [663, 0],
 [664, 2],
 [665, 0],
 [666, 0],
 [667, 0],
 [668, 0],
 [669, 0],
 [670, 1],
 [671, 0],
 [672, 0],
 [673, 0],
 [674, 0],
 [675, 0],
 [676, 0],
 [677, 0],
 [678, 0],
 [679, 0],
 [680, 0],
 [681, 0],
 [682, 1],
 [683, 0],
 [684, 1],
 [685, 0],
 [686, 0],
 [687, 1],
 [688, 0],
 [689, 0],
 [690, 1],
 [691, 1],
 [692, 0],
 [693, 0],
 [694, 0],
 [695, 0],
 [696, 0],
 [697, 0],
 [698, 0],
 [699, 1],
 [700, 1],
 [701, 2],
 [702, 2],
 [703, 0],
 [704, 0],
 [705, 0],
 [706, 0],
 [707, 0],
 [708, 0],
 [709, 0],
 [710, 0],
 [711, 0],
 [712, 0],
 [713, 0],
 [714, 0],
 [715, 0],
 [716, 0],
 [717, 0],
 [718, 0],
 [719, 0],
 [720, 0],
 [721, 1],
 [722, 0],
 [723, 0],
 [724, 0],
 [725, 0],
 [726, 0],
 [727, 0],
 [728, 0],
 [729, 0],
 [730, 0],
 [731, 0],
 [732, 0],
 [733, 2],
 [734, 2],
 [735, 0],
 [736, 2],
 [737, 1],
 [738, 1],
 [739, 1],
 [740, 0],
 [741, 0],
 [742, 0],
 [743, 0],
 [744, 0],
 [745, 0],
 [746, 0],
 [747, 0],
 [748, 0],
 [749, 0],
 [750, 0],
 [751, 0],
 [752, 0],
 [753, 0],
 [754, 0],
 [755, 0],
 [756, 0],
 [757, 0],
 [758, 2],
 [759, 0],
 [760, 0],
 [761, 0],
 [762, 0],
 [763, 1],
 [764, 1],
 [765, 0],
 [766, 1],
 [767, 1],
 [768, 1],
 [769, 0],
 [770, 1],
 [771, 0],
 [772, 1],
 [773, 1],
 [774, 0],
 [775, 1],
 [776, 1],
 [777, 0],
 [778, 0],
 [779, 0],
 [780, 0],
 [781, 0],
 [782, 0],
 [783, 0],
 [784, 0],
 [785, 0],
 [786, 0],
 [787, 0],
 [788, 0],
 [789, 0],
 [790, 0],
 [791, 0],
 [792, 0],
 [793, 0],
 [794, 0],
 [795, 0],
 [796, 0],
 [797, 0],
 [798, 0],
 [799, 0],
 [800, 0],
 [801, 0],
 [802, 0],
 [803, 1],
 [804, 0],
 [805, 0],
 [806, 0],
 [807, 0],
 [808, 0],
 [809, 0],
 [810, 0],
 [811, 0],
 [812, 0],
 [813, 0],
 [814, 0],
 [815, 0],
 [816, 0],
 [817, 0],
 [818, 0],
 [819, 0],
 [820, 0],
 [821, 0],
 [822, 0],
 [823, 0],
 [824, 0],
 [825, 0],
 [826, 0],
 [827, 0],
 [828, 0],
 [829, 0],
 [830, 0],
 [831, 0],
 [832, 0],
 [833, 1],
 [834, 0],
 [835, 0],
 [836, 0],
 [837, 0],
 [838, 0],
 [839, 0],
 [840, 0],
 [841, 0],
 [842, 0],
 [843, 0],
 [844, 0],
 [845, 0],
 [846, 0],
 [847, 0],
 [848, 0],
 [849, 0],
 [850, 0],
 [851, 0],
 [852, 0],
 [853, 0],
 [854, 0],
 [855, 0],
 [856, 0],
 [857, 0],
 [858, 0],
 [859, 0],
 [860, 0],
 [861, 0],
 [862, 0],
 [863, 0],
 [864, 0],
 [865, 0],
 [866, 0],
 [867, 0],
 [868, 0],
 [869, 0],
 [870, 0],
 [871, 0],
 [872, 0],
 [873, 0],
 [874, 0],
 [875, 0],
 [876, 0],
 [877, 0],
 [878, 0],
 [879, 0],
 [880, 0],
 [881, 0],
 [882, 1],
 [883, 0],
 [884, 0],
 [885, 0],
 [886, 0],
 [887, 0],
 [888, 0],
 [889, 0],
 [890, 1],
 [891, 0],
 [892, 0],
 [893, 0],
 [894, 2],
 [895, 0],
 [896, 0],
 [897, 0],
 [898, 0],
 [899, 0],
 [900, 0],
 [901, 0],
 [902, 0],
 [903, 0],
 [904, 0],
 [905, 1],
 [906, 0],
 [907, 0],
 [908, 1],
 [909, 0],
 [910, 0],
 [911, 0],
 [912, 0],
 [913, 0],
 [914, 0],
 [915, 0],
 [916, 0],
 [917, 0],
 [918, 0],
 [919, 0],
 [920, 0],
 [921, 0],
 [922, 0],
 [923, 0],
 [924, 0],
 [925, 0],
 [926, 0],
 [927, 0],
 [928, 0],
 [929, 0],
 [930, 0],
 [931, 0],
 [932, 0],
 [933, 0],
 [934, 0],
 [935, 0],
 [936, 0],
 [937, 0],
 [938, 0],
 [939, 0],
 [940, 0],
 [941, 0],
 [942, 0],
 [943, 0],
 [944, 0],
 [945, 0],
 [946, 0],
 [947, 0],
 [948, 0],
 [949, 0],
 [950, 0],
 [951, 0],
 [952, 0],
 [953, 0],
 [954, 1],
 [955, 0],
 [956, 0],
 [957, 0],
 [958, 0],
 [959, 1],
 [960, 0],
 [961, 0],
 [962, 0],
 [963, 0],
 [964, 1],
 [965, 2],
 [966, 1],
 [967, 1],
 [968, 1],
 [969, 1],
 [970, 1],
 [971, 2],
 [972, 0],
 [973, 0],
 [974, 0],
 [975, 0],
 [976, 0],
 [977, 0],
 [978, 1],
 [979, 0],
 [980, 0],
 [981, 0],
 [982, 0],
 [983, 0],
 [984, 0],
 [985, 0],
 [986, 1],
 [987, 0],
 [988, 0],
 [989, 0],
 [990, 0],
 [991, 0],
 [992, 0],
 [993, 1],
 [994, 0],
 [995, 0],
 [996, 0],
 [997, 0],
 [998, 0],
 [999, 0],
 ...]

In [86]:
x_values = [item[0] for item in quote_distr]
y_values = [item[1] for item in quote_distr]

# Create bar plot
fig = px.bar(x=x_values, y=y_values, labels={'x': 'Liedvers', 'y': 'zitierende Predigten'}, title="Zitate aus „Wie schön leuchtet der Morgenstern“ je Liedvers")
fig.show()

In [23]:
# when do quote types spike?

sermon = Sermon("E000036")

In [57]:
def year_helper(year):
    year_finder = re.compile(r'[0-9]{4}')
    year_cleaned = re.findall(year_finder, year)[0]
    return int(year_cleaned)

In [101]:
quotes_per_year = []
sermons_per_year = []
for id in ids:
    sermon_quotes = 0
    source_quotes = 0
    song_quotes = 0

    sermon = Sermon(id)

    year = year_helper(sermon.erscheinungsjahr)
    link = f'<a href="https://orgelpredigt.ur.de/{id}" target="_blank">{sermon.kurztitel}</a>'
    sermons_per_year.append([year, sermon.kurztitel, link])

    all_quotes = set(sermon.all_references)
    for quote in all_quotes:
        if quote.startswith("E00"):
            sermon_quotes += 1
        elif quote.startswith("E08") or quote.startswith("E09"):
            source_quotes += 1
        elif quote.startswith("E10"):
            song_quotes += 1
    quotes_per_year.append([year, [sermon_quotes, source_quotes, song_quotes]])

In [103]:
quotes_per_year

[[1602, [0, 7, 0]],
 [1605, [0, 1, 0]],
 [1606, [0, 8, 5]],
 [1610, [0, 3, 1]],
 [1621, [0, 13, 1]],
 [1624, [0, 23, 0]],
 [1628, [0, 6, 1]],
 [1647, [1, 20, 8]],
 [1648, [2, 11, 8]],
 [1651, [1, 24, 7]],
 [1652, [2, 15, 5]],
 [1660, [1, 10, 1]],
 [1664, [0, 7, 4]],
 [1666, [0, 11, 3]],
 [1667, [0, 10, 8]],
 [1671, [0, 15, 4]],
 [1672, [0, 5, 12]],
 [1673, [3, 10, 4]],
 [1675, [3, 6, 5]],
 [1676, [2, 12, 13]],
 [1676, [0, 14, 8]],
 [1680, [3, 10, 7]],
 [1681, [0, 15, 18]],
 [1683, [1, 10, 16]],
 [1685, [2, 12, 1]],
 [1686, [0, 32, 7]],
 [1687, [1, 45, 1]],
 [1689, [0, 24, 1]],
 [1695, [1, 23, 3]],
 [1696, [1, 10, 0]],
 [1700, [0, 13, 10]],
 [1704, [0, 28, 3]],
 [1704, [2, 49, 3]],
 [1709, [1, 7, 1]],
 [1709, [0, 15, 5]],
 [1711, [2, 49, 15]],
 [1711, [0, 15, 2]],
 [1720, [2, 104, 5]],
 [1721, [0, 13, 0]],
 [1721, [3, 12, 11]],
 [1721, [2, 1, 1]],
 [1726, [0, 4, 5]],
 [1727, [0, 8, 6]],
 [1728, [0, 157, 8]],
 [1730, [0, 5, 6]],
 [1735, [0, 11, 17]],
 [1737, [0, 1, 6]],
 [1739, [2, 20, 3]],
 [1740, [0, 1, 3]],
 [1747, [0, 5, 9]],
 [1749, [1, 34, 25]],
 [1749, [0, 1, 2]],
 [1751, [0, 0, 0]],
 [1753, [0, 1, 1]],
 [1761, [1, 34, 7]],
 [1765, [0, 7, 3]],
 [1766, [0, 0, 1]],
 [1767, [0, 0, 3]],
 [1770, [0, 0, 2]],
 [1778, [0, 0, 0]],
 [1781, [0, 0, 0]],
 [1781, [0, 0, 6]],
 [1795, [0, 0, 0]],
 [1797, [0, 0, 1]],
 [1798, [0, 0, 3]]]

In [93]:
sermons_per_year

[[1602,
  'Christliche Predigt (Tübingen 1602)',
  '<a href="https://orgelpredigt.ur.de/E000001" target="_blank">Christliche Predigt (Tübingen 1602)</a>'],
 [1605,
  'Musica instrumentalis (Meißen 1605)',
  '<a href="https://orgelpredigt.ur.de/E000002" target="_blank">Musica instrumentalis (Meißen 1605)</a>'],
 [1606,
  'Christliche Predigt (Tübingen 1606)',
  '<a href="https://orgelpredigt.ur.de/E000029" target="_blank">Christliche Predigt (Tübingen 1606)</a>'],
 [1610,
  'Elogium Organi Musici (Altenburg 1610)',
  '<a href="https://orgelpredigt.ur.de/E000030" target="_blank">Elogium Organi Musici (Altenburg 1610)</a>'],
 [1621,
  'Corona Templi (Nürnberg 1621)',
  '<a href="https://orgelpredigt.ur.de/E000099" target="_blank">Corona Templi (Nürnberg 1621)</a>'],
 [1624,
  'Vlmische Orgel Predigt (Ulm 1624)',
  '<a href="https://orgelpredigt.ur.de/E000003" target="_blank">Vlmische Orgel Predigt (Ulm 1624)</a>'],
 [1628,
  'Musica ecclesiastica (Stettin 1628)',
  '<a href="https://orgelpredigt.ur.de/E000098" target="_blank">Musica ecclesiastica (Stettin 1628)</a>'],
 [1647,
  'Kostbare Bosische Orgel (Zwickau 1647)',
  '<a href="https://orgelpredigt.ur.de/E000096" target="_blank">Kostbare Bosische Orgel (Zwickau 1647)</a>'],
 [1648,
  'Längst=gewüntzschte Mittweidische Orgel=Freude (Dresden 1648)',
  '<a href="https://orgelpredigt.ur.de/E000095" target="_blank">Längst=gewüntzschte Mittweidische Orgel=Freude (Dresden 1648)</a>'],
 [1651,
  'Organologismos (Dresden 1651)',
  '<a href="https://orgelpredigt.ur.de/E000092" target="_blank">Organologismos (Dresden 1651)</a>'],
 [1652,
  'Stolpenische Ehren-Crone (Dresden 1652)',
  '<a href="https://orgelpredigt.ur.de/E000091" target="_blank">Stolpenische Ehren-Crone (Dresden 1652)</a>'],
 [1660,
  'Organolustria Evangelico-Stambachiana (Hof 1660)',
  '<a href="https://orgelpredigt.ur.de/E000090" target="_blank">Organolustria Evangelico-Stambachiana (Hof 1660)</a>'],
 [1664,
  'Encoenia HierOrganica (Halle 1664)',
  '<a href="https://orgelpredigt.ur.de/E000089" target="_blank">Encoenia HierOrganica (Halle 1664)</a>'],
 [1666,
  'Orgel=Predigt (Arnstadt 1666)',
  '<a href="https://orgelpredigt.ur.de/E000086" target="_blank">Orgel=Predigt (Arnstadt 1666)</a>'],
 [1667,
  'Das fröliche Hallelujah (Halle 1667)',
  '<a href="https://orgelpredigt.ur.de/E000085" target="_blank">Das fröliche Hallelujah (Halle 1667)</a>'],
 [1671,
  'Das Gott=Lob=Schallende Hosianna (Leipzig 1671)',
  '<a href="https://orgelpredigt.ur.de/E000083" target="_blank">Das Gott=Lob=Schallende Hosianna (Leipzig 1671)</a>'],
 [1672,
  'Geistliches Orgelwerk (Erfurt 1672)',
  '<a href="https://orgelpredigt.ur.de/E000082" target="_blank">Geistliches Orgelwerk (Erfurt 1672)</a>'],
 [1673,
  'Denck- und Danck-Säule (Rothenburg ob der Tauber [1673])',
  '<a href="https://orgelpredigt.ur.de/E000079" target="_blank">Denck- und Danck-Säule (Rothenburg ob der Tauber [1673])</a>'],
 [1675,
  'Das fröliche Halleluja (Wittenberg 1675)',
  '<a href="https://orgelpredigt.ur.de/E000078" target="_blank">Das fröliche Halleluja (Wittenberg 1675)</a>'],
 [1676,
  'Das Lieblich=klingende Orgeln und Saiten=Spiel (Coburg 1676)',
  '<a href="https://orgelpredigt.ur.de/E000075" target="_blank">Das Lieblich=klingende Orgeln und Saiten=Spiel (Coburg 1676)</a>'],
 [1676,
  'Die andere Predigt (Coburg 1676)',
  '<a href="https://orgelpredigt.ur.de/E000106" target="_blank">Die andere Predigt (Coburg 1676)</a>'],
 [1680,
  'Geistlich= und Gott wohlgefälliges Lob- und Danck-Opffer (Bayreuth 1680)',
  '<a href="https://orgelpredigt.ur.de/E000073" target="_blank">Geistlich= und Gott wohlgefälliges Lob- und Danck-Opffer (Bayreuth 1680)</a>'],
 [1681,
  'Gott und Gnug (Meißen 1681)',
  '<a href="https://orgelpredigt.ur.de/E000072" target="_blank">Gott und Gnug (Meißen 1681)</a>'],
 [1683,
  'Cithara Theologica (Schleusingen 1683)',
  '<a href="https://orgelpredigt.ur.de/E000070" target="_blank">Cithara Theologica (Schleusingen 1683)</a>'],
 [1685,
  'Organi Laudes (Plauen 1685)',
  '<a href="https://orgelpredigt.ur.de/E000108" target="_blank">Organi Laudes (Plauen 1685)</a>'],
 [1686,
  'Organum Mysticum (Dresden 1686)',
  '<a href="https://orgelpredigt.ur.de/E000069" target="_blank">Organum Mysticum (Dresden 1686)</a>'],
 [1687,
  'Das dem Allmächtigen abzustattende Lob (Altenburg s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000068" target="_blank">Das dem Allmächtigen abzustattende Lob (Altenburg s.a.)</a>'],
 [1689,
  'Organo-Praxis Mystica (Görlitz 1689)',
  '<a href="https://orgelpredigt.ur.de/E000067" target="_blank">Organo-Praxis Mystica (Görlitz 1689)</a>'],
 [1695,
  'Eine Christliche Orgel=Predigt (Danzig 1695)',
  '<a href="https://orgelpredigt.ur.de/E000065" target="_blank">Eine Christliche Orgel=Predigt (Danzig 1695)</a>'],
 [1696,
  'Schuldiges Lob Gottes (Nürnberg 1696)',
  '<a href="https://orgelpredigt.ur.de/E000063" target="_blank">Schuldiges Lob Gottes (Nürnberg 1696)</a>'],
 [1700,
  'Die Christliche Harmonie (Jena 1700)',
  '<a href="https://orgelpredigt.ur.de/E000060" target="_blank">Die Christliche Harmonie (Jena 1700)</a>'],
 [1704,
  'Christliche Orgel-Predigt (Danzig s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000058" target="_blank">Christliche Orgel-Predigt (Danzig s.a.)</a>'],
 [1704,
  'Einweihungs-Predigt (Görlitz 1704)',
  '<a href="https://orgelpredigt.ur.de/E000059" target="_blank">Einweihungs-Predigt (Görlitz 1704)</a>'],
 [1709,
  'Orgel Weih-Predigt (Ansbach 1709)',
  '<a href="https://orgelpredigt.ur.de/E000056" target="_blank">Orgel Weih-Predigt (Ansbach 1709)</a>'],
 [1709,
  'Das rein-gestimmte Orgel-Werk unsers Herzens (Nürnberg s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000057" target="_blank">Das rein-gestimmte Orgel-Werk unsers Herzens (Nürnberg s.a.)</a>'],
 [1711,
  'Davids Vermahnung (Dresden 1711)',
  '<a href="https://orgelpredigt.ur.de/E000055" target="_blank">Davids Vermahnung (Dresden 1711)</a>'],
 [1711,
  'Evangelischer Christen Gott-gefällige Kirch-Weyhung (Dresden 1711)',
  '<a href="https://orgelpredigt.ur.de/E000104" target="_blank">Evangelischer Christen Gott-gefällige Kirch-Weyhung (Dresden 1711)</a>'],
 [1720,
  'Vivum Dei Organum (Schneeberg s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000053" target="_blank">Vivum Dei Organum (Schneeberg s.a.)</a>'],
 [1721,
  'Die Kneiphöffsche laute Orgel=Stimme (Königsberg 1721)',
  '<a href="https://orgelpredigt.ur.de/E000051" target="_blank">Die Kneiphöffsche laute Orgel=Stimme (Königsberg 1721)</a>'],
 [1721,
  'Ein wolgerührtes Orgel=Werck (Königsberg 1721)',
  '<a href="https://orgelpredigt.ur.de/E000052" target="_blank">Ein wolgerührtes Orgel=Werck (Königsberg 1721)</a>'],
 [1721,
  'Glaubiger Kinder Gottes Gott=gefällige Music (Augsburg 1721)',
  '<a href="https://orgelpredigt.ur.de/E000074" target="_blank">Glaubiger Kinder Gottes Gott=gefällige Music (Augsburg 1721)</a>'],
 [1726,
  'Die verstimmte Zwölff Grösseste Pfeiffen (Tübingen s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000048" target="_blank">Die verstimmte Zwölff Grösseste Pfeiffen (Tübingen s.a.)</a>'],
 [1727,
  'Die edle und wohlgeordnete Music der Gläubigen (Halle 1727)',
  '<a href="https://orgelpredigt.ur.de/E000046" target="_blank">Die edle und wohlgeordnete Music der Gläubigen (Halle 1727)</a>'],
 [1728,
  'Hymnosophia sacra (Billwerder 1728)',
  '<a href="https://orgelpredigt.ur.de/E000045" target="_blank">Hymnosophia sacra (Billwerder 1728)</a>'],
 [1730,
  'Einweihungs-Predigt (Berlin 1730)',
  '<a href="https://orgelpredigt.ur.de/E000061" target="_blank">Einweihungs-Predigt (Berlin 1730)</a>'],
 [1735,
  'Das Neue Lied (Freiberg 1735)',
  '<a href="https://orgelpredigt.ur.de/E000042" target="_blank">Das Neue Lied (Freiberg 1735)</a>'],
 [1737,
  'Stimme des Predigers (1737)',
  '<a href="https://orgelpredigt.ur.de/E000109" target="_blank">Stimme des Predigers (1737)</a>'],
 [1739,
  'Die Billige Orgel-Freude (Danzig 1739)',
  '<a href="https://orgelpredigt.ur.de/E000041" target="_blank">Die Billige Orgel-Freude (Danzig 1739)</a>'],
 [1740,
  'Winnedisches Reminiscere (Stuttgart 1740)',
  '<a href="https://orgelpredigt.ur.de/E000039" target="_blank">Winnedisches Reminiscere (Stuttgart 1740)</a>'],
 [1747,
  'Den rechtmäßigen Gebrauch der Music (Königsberg 1747)',
  '<a href="https://orgelpredigt.ur.de/E000038" target="_blank">Den rechtmäßigen Gebrauch der Music (Königsberg 1747)</a>'],
 [1749,
  'Die heilige Sabbaths-Lust an dem Herrn (Danzig 1749)',
  '<a href="https://orgelpredigt.ur.de/E000036" target="_blank">Die heilige Sabbaths-Lust an dem Herrn (Danzig 1749)</a>'],
 [1749,
  'Christliche Predigt (Straßburg 1749)',
  '<a href="https://orgelpredigt.ur.de/E000037" target="_blank">Christliche Predigt (Straßburg 1749)</a>'],
 [1751,
  'Musicalische Orgel= Lob= und Ehren=Predigt (s.l. 1751)',
  '<a href="https://orgelpredigt.ur.de/E000035" target="_blank">Musicalische Orgel= Lob= und Ehren=Predigt (s.l. 1751)</a>'],
 [1753,
  'Lob= und Danck=Predigt (Berlin 1753)',
  '<a href="https://orgelpredigt.ur.de/E000034" target="_blank">Lob= und Danck=Predigt (Berlin 1753)</a>'],
 [1761,
  'Der Christen gerechte Freude (Breslau 1761)',
  '<a href="https://orgelpredigt.ur.de/E000027" target="_blank">Der Christen gerechte Freude (Breslau 1761)</a>'],
 [1765,
  'Die heiligen Verrichtungen in dem Hause des Herrn (Eisenach 1765)',
  '<a href="https://orgelpredigt.ur.de/E000024" target="_blank">Die heiligen Verrichtungen in dem Hause des Herrn (Eisenach 1765)</a>'],
 [1766,
  'Der rechte Gebrauch der Orgeln (Altenburg 1766)',
  '<a href="https://orgelpredigt.ur.de/E000023" target="_blank">Der rechte Gebrauch der Orgeln (Altenburg 1766)</a>'],
 [1767,
  'Das heilige und fröliche Aufsehen (Tübingen 1767)',
  '<a href="https://orgelpredigt.ur.de/E000021" target="_blank">Das heilige und fröliche Aufsehen (Tübingen 1767)</a>'],
 [1770,
  'Predigt am Feste der Heimsuchung Mariae (Rostock 1770)',
  '<a href="https://orgelpredigt.ur.de/E000020" target="_blank">Predigt am Feste der Heimsuchung Mariae (Rostock 1770)</a>'],
 [1778,
  'Der Dienst der Orgeln (Jena 1778)',
  '<a href="https://orgelpredigt.ur.de/E000016" target="_blank">Der Dienst der Orgeln (Jena 1778)</a>'],
 [1781,
  'Gast-Predigt (Ulm 1781)',
  '<a href="https://orgelpredigt.ur.de/E000014" target="_blank">Gast-Predigt (Ulm 1781)</a>'],
 [1781,
  'Rede und Predigt bey Einweihung der neuen Orgel (Stockholm 1781)',
  '<a href="https://orgelpredigt.ur.de/E000015" target="_blank">Rede und Predigt bey Einweihung der neuen Orgel (Stockholm 1781)</a>'],
 [1795,
  'Predigt bey Einweyhung der Orgel (s.l. 1795)',
  '<a href="https://orgelpredigt.ur.de/E000009" target="_blank">Predigt bey Einweyhung der Orgel (s.l. 1795)</a>'],
 [1797,
  'Predigt Bey der Einweihung einer Orgel (Leipzig 1797)',
  '<a href="https://orgelpredigt.ur.de/E000008" target="_blank">Predigt Bey der Einweihung einer Orgel (Leipzig 1797)</a>'],
 [1798,
  'Predigt bey der feyerlichen Einweihung der neuen Orgel (Magdeburg 1798)',
  '<a href="https://orgelpredigt.ur.de/E000007" target="_blank">Predigt bey der feyerlichen Einweihung der neuen Orgel (Magdeburg 1798)</a>']]

In [94]:
colors = {
    'Orgelpredigten': 'rgb(135, 44, 162)',
    'Musikwerke': 'rgb(192, 54, 157)',
    'Literatur': 'rgb(234, 79, 136)'
}

In [95]:
df = pd.DataFrame(sermons_per_year, columns=["year", "title", "id"])
# Create full year range
all_years = pd.DataFrame({"year": range(1600,1801)})

# Merge to ensure every year appears, fill missing with 0
df_full = pd.merge(all_years, df, on="year", how="left").fillna(0)

agg = df.groupby("year").agg({
    "title": lambda x: "<br>".join(x.astype(str)),
    "id": lambda x: ", ".join(x.astype(str)),
    "year": "count"
}).rename(columns={"year": "count"}).reset_index()

In [99]:
fig = px.bar(agg, x='year', y='count',
             hover_data='id',
             color_discrete_sequence=['rgb(135, 44, 162)'])
fig.show()

In [102]:
df = pd.DataFrame(quotes_per_year, columns=["Jahr", "Anzahl"])
df[["Orgelpredigten", "Literatur", "Musikwerke"]] = pd.DataFrame(df["Anzahl"].tolist(), index=df.index)
df = df.drop(columns="Anzahl")

# Melt to long format for plotly express
df_long = df.melt(id_vars="Jahr", value_vars=["Orgelpredigten", "Literatur", "Musikwerke"],
                  var_name="type", value_name="Anzahl")

# Create figure
fig = go.Figure()

# Add line traces with custom colors
for t in df_long["type"].unique():
    subset = df_long[df_long["type"] == t]
    fig.add_trace(
        go.Scatter(
            x=subset["Jahr"],
            y=subset["Anzahl"],
            mode="lines+markers",
            name=t,
            line=dict(color=colors[t], width=2),
            marker=dict(size=8)
        )
    )

# Layout
fig.update_layout(
    title="Zeitliche Verteilung von Zitattypen",
    xaxis_title="Jahr",
    yaxis_title="Anzahl"
)

fig.show()

In [104]:
sermon = Sermon("E000036")

In [122]:
sermon.chunked[0][3]["types"]

['', '', '', '', '', ' bibel', ' bibel']

In [ ]:
t = ["", "", ""]

In [119]:
first_type = ""
for i in t:
    if (len(i) != 0):
        first_type = i
        break
print(first_type)

 .